### ISSUE TITLE
Translation: Wornmodifier not used

### ISSUE THREAD

**Issue by thanosxxx** [textadventures/quest#1007]
I'm using the Greek translation in 5.8.beta5

When wearing an item, the item in the inventory is marked "worn", in English. The wornmodifier, "φορέθηκε", which is defined in the language file, is not used.

**Comment by ThePix** [comment]
This is because the worn modify system was changed to accomodate Italiano, and I forgot to update for Greek (and Deutsche and Espanol). I have now updated the files on Github, but do these languages also need to vary the modifier for gender/number?

**Comment by Pertex** [comment]
no problem in german

**Comment by ThePix** [comment]
Corrected in latest beta
