### ISSUE TITLE
Find and Replace close the search field (probably a minor discrepancy)

### ISSUE THREAD

**Issue by KVonGit** [textadventures/quest#1018]
When editing in full code view, I frequently use Ctrl+F to search for things and Ctrl+H to search & replace.

I press Ctrl+F, and the search field is displayed, and it is in focus (so I can just type and I'm already typing in that field).  Ctrl+H works the same way (of course).

Now, when I Ctrl+F and find what I'm looking for, I frequently need to find something else, so I press Ctrl+F again (which normally just puts the focus on the Find field and selects all the text, so I can just type in my new search string), and the FIND SEARCH FIELD CLOSES?  I have to press Ctrl+F to open it again.  AND, if I'm lucky, I don't accidentally enter that search string into my game's code, thinking I'm typing in the search field when the search is actually closed.  (I don't look at what I'm typing most of the time.  I was trained this way, and I think this is common practice, but I may be mistaken.)

The same things happens with Ctrl+H.  Trying to do a second search and replace while the search and replace field is displayed causes it to close.

I have nearly gone insane while editing a game because of this.  It is a BIG game, and an object name got changed.  I was using Search & Replace to be sure I didn't miss anything...

Once I made all my changes, the game would not load.  It took me quite a while to find all of the text which I had randomly added to the game's code while thinking I was typing in the Search field...

As far as I know, all existing text editors behave like Quest 5.7.2 when pressing Ctrl+F or Ctrl+H during a search.  (Not closing the search field, just putting the cursor back up there and select all the text, so the user can just type in the new search string.)

---
![find_and_replace 1](https://user-images.githubusercontent.com/30656341/40870995-40d5e9e8-65f9-11e8-8a5d-4d5fc683eb44.gif)

**Comment by SoonGames** [comment]
Hello KV.

Yeah, that's right. The behavior is untypical. I must have screwed that up when I put in the buttons. I'll change it.

salute

Sven

**Comment by SoonGames** [comment]
Okay. It's done.

**Comment by KVonGit** [comment]
> I must have screwed that up when I...

I've started so many sentences that way this past week, I've lost count.

You're doing far better than I am when it comes to error-free commits.  

(Sorry about all that, by the way, Pix!)

---
Reference: Pull Request #1019
