### ISSUE TITLE
Margin Colour Change Throws Error in HTML Console (5.8)

### ISSUE THREAD

**Issue by KVonGit** [textadventures/quest#1027]
When setting the margin colour in Quest 5.8.0, the margin colour is set correctly, but there is an error in the HTML console if I change that setting in the GUI.

```Uncaught ReferenceError: setBackground is not defined```

Of course ```setBackground()``` *is* defined when I look in the console...

...and the colour *does* change.   But, it is throwing an error for some reason.

I just checked, and **this does not happen if I change the ASL version to 550** before starting the game in Quest 5.8.0 (the recent beta).   

This thoroughly confuses me.  I found this out by changing the ASL version so I could test the game in 5.7.2.  When it worked with no error, I switched back to 5.8.0 and the ASL version stuck at 550 at first because I did not change anything in the editor.

Here's the game (but it's just a blank game with game.marginscolour set to "Brown").

```xml
<!--Saved by Quest 5.8.6733.15539-->
<asl version="580">
  <include ref="English.aslx" />
  <include ref="Core.aslx" />
  <game name="fjadslfjasl">
    <gameid>5c384d85-d125-49e6-86c1-68e990740341</gameid>
    <version>1.0</version>
    <firstpublished>2018</firstpublished>
    <marginscolour>Brown</marginscolour>
  </game>
  <object name="room">
    <inherit name="editor_room" />
    <isroom />
    <object name="player">
      <inherit name="editor_object" />
      <inherit name="editor_player" />
    </object>
  </object>
</asl>
```

**Comment by ThePix** [comment]
I tried that game, but I do not see the error.

**Comment by KVonGit** [comment]
Huh...

Did you open the HTML Tools window and check the console?  That's where the error is for me.  (My computer may still be upset since this latest Windows update.)

**Comment by KVonGit** [comment]
Scratch that last question.

I just checked it out on my friend's Windows 10 machine and then on my Windows 7 machine, and this only happens on my Windows 10 machine, with which I have recently had quite a few problems.

Closing this one out.  Cried "wolf."
