### ISSUE TITLE
Error with unopened container (Quest 5.8 Beta 10)

### ISSUE THREAD

**Issue by SoonGames** [textadventures/quest#1034]
If I want to place an object in an unopened container this error occurs:

Error running script: Error evaluating expression 'HasString(obj, "alias")': HasString function expected object parameter but was passed 'null'
Error running script: Error compiling expression 'obj.gender': Variable does not refer to an object: 'obj'
not open.

![image](https://user-images.githubusercontent.com/30032863/41822058-3023220c-77ea-11e8-8900-125b3e5a1f0a.png)

**Comment by ThePix** [comment]
Thanks for spotting
