### ISSUE TITLE
Backspace clears screen

### ISSUE THREAD

**Issue by ThePix** [textadventures/quest#1041]
Reported by DavyB on [this thread](http://textadventures.co.uk/forum/quest/topic/hpfc9gd6eeknh3tctegx3a/quest-5-8-beta), backspace will make the browser go back one page, i.e., clear the screen.

Looks like this will stop it, but at the moment, I consider Quest closed to changes as it awaits uploading.
```
// Disables backspace outside of the command bar
// Otherweise backspace jumps the browser to the previous page, and the game disappears
$(function(){
    var rx = /INPUT|SELECT|TEXTAREA/i;

    $(document).bind("keydown keypress", function(e){
        if( e.which == 8 ){ // 8 == backspace
            if(!rx.test(e.target.tagName) || e.target.disabled || e.target.readOnly ){
                e.preventDefault();
            }
        }
    });
});

**Comment by KVonGit** [comment]
@ThePix 

Should I test this out while I've still got Visual Studio installed to test things on all three Quest platforms (desktop, webplayer, and mobile)?

Or maybe you tested it already, but it was too late to include it in 5.8? (I seem to remember this happening that way.)

Either way, I could make a pull request for it, while I'm already working on some. Just say the word if you want me to.

**Comment by KVonGit** [comment]
@alexwarren 

The CEF update fixed this.
