### ISSUE TITLE
Textprocessor {exit:room2} does not display link

### ISSUE THREAD

**Issue by Pertex** [textadventures/quest#1043]
When you use the exit-tag of the textprocessor, there is no link displayed (only the alias of the room). Other tags like command or object are working correct

**Comment by ThePix** [comment]
It works for me. Can you give some example code?

**Comment by ThePix** [comment]
Looks like this is not actually an issue:
http://textadventures.co.uk/forum/quest/topic/vprkcuodqeqn41fkyvhgrw/exit-links-not-displaying#260aef24-050c-4aec-860f-ec8239b92baf
