### ISSUE TITLE
5.72 Crash on any game launch

### ISSUE THREAD

**Issue by RNGLillian** [textadventures/quest#1049]
Whenever I try to launch any game, I get his error message "Error launching game: Could not load file or assembly 'CefSharp.Core.dll' or one of it dependencies. is not a valid Win32 application. (Exception from HRESULT: 0x800700C1)" I am on Windows 10 and have verified that no antivirus programs are interfering. This also seems to happen in 5.80 for me.

**Comment by zeo335** [comment]
Same, I've been using Quest for almost 5 years I think and never had any problems then the newest update came out and for 4 months it kept saying it was updated but it never updated now it updates and the first thing I try to run it crashed... it gave me this error code... dunno if it helps I'm not uber tech-savvy tbh.
System.MissingMethodException: Method not found: 'Void TextAdventures.Quest.EditorControls.WFEditorTree.SetMenuSeparatorVisible(System.String, Boolean)'.
   at TextAdventures.Quest.Editor.SetTreeMenuVisibility()
   at TextAdventures.Quest.Editor.set_EditorStyle(EditorStyle value)
   at TextAdventures.Quest.Editor._Closure$__64-0._Lambda$__0()

**Comment by RNGLillian** [comment]
Download size for 5.72 download was 31,261,521 bytes. Crashed with same error when I hit play.

**Comment by ThePix** [comment]
Why not use Quest 5.8?

**Comment by RNGLillian** [comment]
The particular game I am trying to play is not updated to 5.8 yet. Plus, I have also tested 5.8 in the past, and exactly the same thing happens.

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
