### ISSUE TITLE
Quest 5.8 Ask/Tell Tab Not Showing Up

### ISSUE THREAD

**Issue by DeemDeem52** [textadventures/quest#1050]
When I look at the "Features" tab for any given object, I find that I cannot enable the Ask/Tell tab because there is not option to do so. What could be the problem and is there a fix?

Thank you!

**Comment by ThePix** [comment]
You need to turn it on on the features tab of the game object first.

To be honest, I have no idea why it is different to everything else. This is not a bug, so I will not be doing anything about it urgently, but I will leave this open as a possible improvement somewhere down the line.

**Comment by DeemDeem52** [comment]
When I look at the Features tab for the object, I see all of the checkboxes except for the Ask/Tell box. Is this a glitch?

![qglitch](https://user-images.githubusercontent.com/42725035/44791312-8ddac380-ab5e-11e8-8df8-2eefae665147.PNG)

**Comment by Selsynn** [comment]
@DeemDeem52 The option is in the tab of the **game** object

![asktellimgforquest](https://user-images.githubusercontent.com/7371599/44796206-81fcfa80-ab7a-11e8-8760-bd979478f1db.PNG)

**Comment by DeemDeem52** [comment]
Oh, thank you! I feel silly now for not checking that before!
