### ISSUE TITLE
Problem when Previously Worn Items are Renamed

### ISSUE THREAD

**Issue by DWBustard** [textadventures/quest#1059]
Hopefully the following sequence is self explanatory. When an item is worn, taken off, renamed (via alias), then put on again using the new name, its old name is displayed in the inventory:
`> take basin
You pick it up.
> wear basin
You put it on.
> remove basin
You take it off.
> rename basin (this is just basin.alias = helmet)
> inv
You are carrying a helmet.
> wear helmet
You put it on.
> inv
You are carrying a basin (worn).`

DavyB

**Comment by ThePix** [comment]
Try:
```
SetAlias(basin, "helmet")

**Comment by ThePix** [comment]
You might want to edit your post so it does not your e-mail address, or indeed all that boiler plate stuff!

**Comment by ThePix** [comment]
I think this is resolved.
