### ISSUE TITLE
[5.8] Popup error on clicking any game object while editing any game

### ISSUE THREAD

**Issue by FibrielSolaer** [textadventures/quest#1063]
I am using Windows 10 Home.

I've just updated from Quest 5.7.1 to 5.8 and receive an error every time any game element is selected (object, Function, Object Group, etc.) when editing any game. This includes immediately when opening any game for editing.

This error occurs both on existing games as well as in new games created within 5.8.

After this error occurs once, mousing over the game's object tree, or over any of the top bar options, produces the "waiting..." mouse cursor. If the game is closed, the "waiting..." cursor also displays when mousing over the Create new game / Open an existing game / Read the Tutorial options.

Other than being annoying, this error does not seem to damage game data or prevent playing games. It just makes editing games very slow and obnoxious.

> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
>    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    at TextAdventures.Quest.EditorControls.WFEditorTree.SetMenuEnabled(String key, Boolean enabled)
>    at TextAdventures.Quest.Editor.UpdateClipboardButtons()
>    at TextAdventures.Quest.Editor.ShowEditor(String key)
>    at TextAdventures.Quest.Editor.ctlTree_SelectionChanged(String key)
>    at TextAdventures.Quest.EditorControls.WFEditorTree.ChangeSelection(String key)
>    at TextAdventures.Quest.EditorControls.WFEditorTree.SelectCurrentTreeViewItem()
>    at TextAdventures.Quest.EditorControls.WFEditorTree.ctlTreeView_AfterSelect(Object sender, TreeViewEventArgs e)
>    at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
>    at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
>    at System.Windows.Forms.TreeView.WmNotify(Message& m)
>    at System.Windows.Forms.TreeView.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
