### ISSUE TITLE
Moved file where projects and published games are stored to flash drive. Now cannot create new games.

### ISSUE THREAD

**Issue by Alphamoonman** [textadventures/quest#1100]
I cut and pasted the folder responsible for storing published or in-development games (This includes its parent folder) to my E: (which is a flash drive) where Quest was originally installed. I set in options that the quest games folder is where my creations go, and downloaded games are where downloaded games go. Despite trying to set up where a newly created game will go (that being the Quest games folder) it will not let me click the button to start the project and create the file.

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
