### ISSUE TITLE
Touchscreen of Windows 11 doesn't work with Quest

### ISSUE THREAD

**Issue by shawny43** [textadventures/quest#1128]
No error logs found. But touch screen broken with Quest client. But from browser is working. But Online is bugged a lot due to instability from server side. Proof when i used spacedesk with touchscreen support or Chrome Remote Desktop in any win32 works except Quest. Soo explain whats wrong or whats i did that wrong.

OS: Windows 11 Home Edition (Before: Windows 10 Home Edition)
OS Ver: 22000.282 - 21h2
PC PreBuild: Acer TC-885-EB17
Processor/Graphics: Intel 9th Gen i5 9400 / UHD Graphics 630
Memory: 12GB DDR4

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
