### ISSUE TITLE
Big problems with mobiles.

### ISSUE THREAD

**Issue by shawny43** [textadventures/quest#1129]
Keyboard glitching due to the Quest game screen doesn't resize imself like others apps does that broke the experience wich is impossible to play on mobile from web pages and again Android and iOS automatically show up keyboard that start bugged and make unplayable from the quest screen. And again web page is not playable at all due they sometimes be broken or just doesn't respond on interact with the game that force to reload the game from the main. Reload from browser was horrible beacause the browser sometimes return into problem from server side. 

Where the mobile client version of quest? Is in the planning? Quest is an open-source project? How i can play with all theses problems?

**Comment by ThePix** [comment]
There is a mobile version, you can find the code here:
https://github.com/textadventures/quest/tree/master/WebPlayer/Mobile

I would guess Quest is failing to identify your device as mobile, but have to admit I am not that familiar with the underlying code.

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
