### ISSUE TITLE
Quest Software MP3 files don't make sound

### ISSUE THREAD

**Issue by Gigabit-Bug** [textadventures/quest#1156]
For some reason i can't hear my MP3 files when they play, even though they've worked before.

**Comment by KVonGit** [comment]
Sorry to have just now read this. If you are still interested:

Are you using the desktop player when you can't hear MP3 files?

If yes, that is because Quest's built-in browser in the desktop version cannot play MP3 files due to proprietary reasons.

**Comment by KVonGit** [comment]
UPDATE

I was mistaken. You can play MP3 files using `play sound` in the desktop version of Quest 5.8. (It also played a FLAC file, to my surprise.)

I'm doing it right now, just to test it.

Be sure you have "Play sounds" checked in Options in the Quest player.

![image](https://github.com/user-attachments/assets/9e1a8444-6807-4cf5-bdc7-e64f88acb6ec)

---
Are you on Windows 10?
