### ISSUE TITLE
saving issue on website

### ISSUE THREAD

**Issue by vurt834** [textadventures/quest#1177]
Hi, saving has been an issue on the website for awhile, any indications as to when it will be fixed? I've posted to the discrussion forums about it, but have received no replies. Or perhaps the problem is on my end? Using the desktop editor. I've tried saving in other games as well, and it doesn't seem to work there either.

**Comment by KVonGit** [comment]
Hello,

Just to notify you, they fixed the saving issue on the site yesterday.

https://textadventures.co.uk/forum/quest/topic/yndb1wg4p0yke-o7egn6hq/saving-games-online-is-now-fixed

Happy gaming!
