### ISSUE TITLE
Switch function does not work

### ISSUE THREAD

**Issue by pandadrivers** [textadventures/quest#1180]
I follow the tutorial, at the Custom commands page at the bottem there is an explanation about the switch function.
But when I do this and run the game I am getting an error on the keys: Error running script: Error compiling expression 'troll': Unknown object or variable 'troll'
![Screenshot_1](https://github.com/textadventures/quest/assets/44341154/aa52f2e9-0889-4f73-aafb-c5b163d755ce)
![Screenshot_2](https://github.com/textadventures/quest/assets/44341154/7edbcdb3-eaf7-461d-abe6-42335f4c50b4)

**Comment by alexwarren** [comment]
You don't have a `troll` object in your game, if you add one this should work.
