### ISSUE TITLE
Only way I can think to attempt to contact someone who works at textadventures.co.uk

### ISSUE THREAD

**Issue by Damariobros** [textadventures/quest#1182]
From what I can tell, everything is falling apart.

It's not possible to register an account. Attempting to do so results in an error page, the username and email get registered, and the confirmation email doesn't get sent and the account can't be used.

It's not possible to use the Contact Us page. Attempting to submit feedback results in an error page.

The social medias have been dead since 2019, so it's not possible to reach you there.

There is no email to contact.

There is no staff monitoring the forums, so people reporting issues there doesn't get seen.

The blog website is just down. Entirely. And has been for at least a month if not longer.

There isn't even a place to submit legal requests such as GDPR.

Someone please get the attention of the textadventures.co.uk staff, admins, devs, literally anyone who works there and can start getting things moving.

**Comment by alexwarren** [comment]
I've recently stepped back in to fix a bunch of issues on the site, after about 7 years away (during which the site was entirely in the hands of other people who didn't always give it the attention it needed).

I've fixed quite a few things, so we're in much better shape now, including:

- emails are working again (for account registration, forgot password etc)
- the contact form works again
- we've got some new moderators on the forums
