### ISSUE TITLE
Using JavaScript doc needs a little touching-up

### ISSUE THREAD

**Issue by KVonGit** [textadventures/quest#1263]
![image](https://github.com/user-attachments/assets/e9aa0b44-e56c-4b4b-9d15-1b1e348e0791)

This statement is biased against game attributes, I think :)

![image](https://github.com/user-attachments/assets/50e6412e-2db1-4a7d-b597-74afc2d045cc)

---
Suggestion:
```
Note: As the `InitUserInterface` function can only be overridden in the desktop version, online authors must use the "User interface initialisation script" under the Advanced Features tab of the `game` object.
```

---
Only problem with the suggestion is: I don't see where this is explained anywhere in the doc.

- [ ] TODO: Write a line or two explaining interface initialization before editing this bit, or at least link to something explaining it.

**Comment by Pertex** [comment]
Does this mean, that this tab is useless in the Webeditor and should removed?

**Comment by angelwedge** [comment]
> Does this mean, that this tab is useless in the Webeditor and should removed?

No; it means that in the webeditor you need to use this tab to make up for the inability to override functions.

> How did you get this message

It's in the documentation. To me, it reads like it was put there before the `game.inituserinterface` script attribute was added as an alternative for the `InitUserInterface` function.

I'm not sure if there is documentation about this distinction anywhere. But I would suggest that documentation proposes the script attribute as the default way to include UI javascript (given that it's easier to modify in the editor). The function could be best kept for libraries which want to sync data between custom editor tabs and their javascript files. Separating the initialisation code like this could reduce the chances of a user stepping on a library's toes (although using multiple UI-heavy libraries could still be problematic… but I don't think that's something many users will want).

**Comment by KVonGit** [comment]
> Does this mean, that this tab is useless in the Webeditor and should removed? How did you get this message

Angel is correct on all counts.

We just need to update it to advise using `game.inituserinterface`, and to explain that script runs each time the game is loaded -- and to explain that the JS needs to be defined each time the game loads (even when resuming from a save), not just in the start script.

Or it might just need to link to other docs that explain all that. I have to look through the docs, to be sure what all is already explained elsewhere.

**Comment by KVonGit** [comment]
Closing this, to reopen after more research.

- https://docs.textadventures.co.uk/quest/functions/corelibrary/inituserinterface.html
- https://docs.textadventures.co.uk/quest/advanced_game_scripts.html
- https://docs.textadventures.co.uk/quest/ui-javascript.html
- https://docs.textadventures.co.uk/quest/webeditor.html#no-overriding-functions-and-commands
- https://docs.textadventures.co.uk/quest/custom_panes.html
