### ISSUE TITLE
Translations of game menus and menu dialog

### ISSUE THREAD

**Issue by alexwarren** [textadventures/quest#285]
The "Cancel" and "Select" buttons on the ShowMenu dialog are currently not
translatable.  

Also need to think about how to handle translating the Player menus.  
## Work Item Details

**Original CodePlex Issue:**    [Issue 911](http://quest.codeplex.com/workitem/911)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Oct 2, 2011 at 10:33 AM
**Reported by:**    alexwarren
**Updated on:** May 9, 2012 at 5:50 PM
**Updated by:** alexwarren

**Comment by alexwarren** [comment]
Check this is handled by the new HTML player.

**Comment by ThePix** [comment]
Hopefully all sorted in 5.8 (thanks to SoonGames)
