### ISSUE TITLE
Turn scripts not called per-command for multi-command input lines

### ISSUE THREAD

**Issue by alexwarren** [textadventures/quest#527]
Turn scripts run at the end of each "turn", but if the user specifies multiple
commands on each line, then the turn script doesn't execute until all commands
have been executed. If the game designer wants to have the game Universe
respond after each command, there is no way to do so currently. It would be
great if turn scripts (or some other per-command mechanism) could allow a
Universe response for each command.  

For example, if background processing is done in a turn script, then "wait"
will have basically the same effect as "wait. wait. wait. wait." which might
be a bit confusing to a player.  

Additional note: according to pertex: "Same with status attributes and
darkness. The function Finishturn is not called in commandqueues."  

I'm not wedded to using turn scripts for this. I'd be happy with any mechanism
that allows me to get control after a command has been executed.  

I imagine (but haven't tested) that walkthroughs have the same problem?  
## Work Item Details

**Original CodePlex Issue:**    [Issue 1153](http://quest.codeplex.com/workitem/1153)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Sep 26, 2012 at 2:04 PM
**Reported by:**    jaynabonne
**Updated on:** May 2, 2013 at 9:04 AM
**Updated by:** alexwarren

**Comment by alexwarren** [comment]
We should get rid of multiple commands on one line, if we haven't already.

**Comment by ThePix** [comment]
I am closing this as multiple commands were removed from Quest (though there is an option to allow them), making this obsolete.
