### ISSUE TITLE
Pass "this" to HandleMultiVerb scripts

### ISSUE THREAD

**Issue by alexwarren** [textadventures/quest#531]
The current HandleMultiVerb scheme is quite flexible - until you want to have
more than one of the same object type. Then in the verb handling scripts,
while you can tell which object the command is targetting, you don't know the
source object. A simple change in HandleMultiVerb to include the source object
as "this" will solve it. This change will be transparent to current code, but
new code could take advantage of it, and it's consistent with "do".  

The new code could be:  

<function name="HandleMultiVerb" parameters="object, property, object2,
default">  

```
dictionary = GetAttribute(object, property)
parameters = NewDictionary()
dictionary add(parameters, "this", object)
if (DictionaryContains(dictionary, object2.name)) {
  invoke (ScriptDictionaryItem(dictionary, object2.name), parameters))
}
else {
  dictionary add (parameters, "object", object2)
  if (DictionaryContains(dictionary, "default")) {
    invoke (ScriptDictionaryItem(dictionary, "default"), parameters)
  }
  else {
    msg (default)
  }
}
```

</function>  
## Work Item Details

**Original CodePlex Issue:**    [Issue 1157](http://quest.codeplex.com/workitem/1157)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Oct 3, 2012 at 12:33 PM
**Reported by:**    jaynabonne
**Updated on:** May 2, 2013 at 9:04 AM
**Updated by:** alexwarren

**Comment by ThePix** [comment]
This looks like it has been done to me. Can it be closed?

**Comment by ThePix** [comment]
No comments, so closing.
