### ISSUE TITLE
Allow a command to match an object, exit or both

### ISSUE THREAD

**Issue by alexwarren** [textadventures/quest#626]
I believe that both issues are caused by the same "bug".  

I just tested the following -- if you type "unlock bathroom" because your exit
has an alias "bathroom" the game will incorrectly set objtype to "object"
instead of "exit" and pass that all the way down from Populate() call in
HandleSingleCommand() into ResolveNextName(). That will in turn call
ResolveName() which will call ResolveNameInternal() and even though
ResolveNameInternal() has the code for exit handling it won't be executed
because it got the wrong objtype as a parameter which means exit won't be
visible and you will get the famous "I can't see that. (bathroom)" message.  

This is really a parsing bug in my opinion, and I am not sure it can be
handled just by changing CoreParser.aslx.  
## Work Item Details

**Original CodePlex Issue:**    [Issue 1252](http://quest.codeplex.com/workitem/1252)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Mar 8, 2013 at 3:19 PM
**Reported by:**    levicki
**Updated on:** Mar 23 at 12:13 PM
**Updated by:** levicki

**Comment by ThePix** [comment]
As of Quest 5.8, you can use "unlock #objectexit#".
