### ISSUE TITLE
"look" directions - add to Features tab

### ISSUE THREAD

**Issue by alexwarren** [textadventures/quest#681]
The ability to make an exit a "look-only" direction should be toggled from the
game features tab.  
## Work Item Details

**Original CodePlex Issue:**    [Issue 1307](http://quest.codeplex.com/workitem/1307)
**Status:** Proposed
**Reason Closed:**  Unassigned
**Assigned to:**    Unassigned
**Reported on:**    Jul 10, 2013 at 3:25 PM
**Reported by:**    alexwarren
**Updated on:** Mar 23 at 12:00 PM
**Updated by:** levicki

**Comment by alexwarren** [comment]
Might want to just get rid of "look only" directions in 6.0 - thinking about getting rid of them for QuestKit anyway. http://forum.textadventures.co.uk/viewtopic.php?f=15&t=5031

**Comment by ThePix** [comment]
Now in Quest 5.7
