### ISSUE TITLE
Problems when playing on iPad and tablets

### ISSUE THREAD

**Issue by GiannisGG** [textadventures/quest#745]
Hello,

Players of my game pointed out what seems to be a bug in regard to the Quest player (browser) on android tablets and iPads: when the game begins, there is a brief text and then the player is prompted to press any key, with the classic "Continue..." Nevertheless, after that, the game gets more or less stuck, as there is one more "Continue..." that never appears, nor does the command line.

The game plays smoothly on desktop browsers.

You can find the game file on this forum post: http://forum.textadventures.co.uk/viewtopic.php?f=10&t=4636

Thanks,
G.

**Comment by alexwarren** [comment]
This has now been fixed in the latest Quest 5.6 code, which will be deployed soon.
