### ISSUE TITLE
looping sound issue

### ISSUE THREAD

**Issue by Silver73** [textadventures/quest#750]
I've had this happen a few times. I set a sound to be looped upon entering a room. Upon entering the room the sound plays once then stops. However restarting the game from the beginning won't replicate the problem; it then works fine. It seems to only ever happen the first time the audio file is played.

**Comment by alexwarren** [comment]
I presume this is when playing online in a browser? If so, audio can be a bit flakey in the browser, although it's got a lot better since online audio support was initially added to Quest. The whole area could definitely use some attention. This might be a good focus for Quest 5.7.

**Comment by Silver73** [comment]
Yeah, online only. It only seems to happen on a first playthrough. If you then quit and then load from the beginning its fine .. perhaps because the file is in the user's cache by that point. Maybe getfileurl before starting the sound loop might trick it. I haven't tried that yet though.

**Comment by ThePix** [comment]
Three years down the line, and plenty of people using audio, I have not heard anyone complain about this. KV in particular did a lot looking at sound files. I am going to assume it is no longer an issue, perhaps because browsers are now better.
