### ISSUE TITLE
Inventory pane / Places and Objects pane / Compass pane should be separate options

### ISSUE THREAD

**Issue by TheOldBrick** [textadventures/quest#752]
In a game that only has non-directional exits, the Compass pane is not necessary. 

Unfortunately, under game / Interface, the Layout option "Show panes (Inventory, Places and Objects, Compass)" is all or nothing; there's only one check box for all three panes.

Please provide three check boxes, one each for Inventory, Places and Objects, Compass. Then, developers can turn off Compass while retaining Inventory, Places and Objects.

**Comment by ThePix** [comment]
This will be in Quest 5.7.
