### ISSUE TITLE
"Background colour" and "Foreground" need enhancement

### ISSUE THREAD

**Issue by TheOldBrick** [textadventures/quest#754]
1. At a minimum, on the "game / Display" tab", "Background colour" and "Foreground" should show a sample of each colour.

Other possible enhancements include:

2. On the "game / Display" tab, for "Background colour" and "Foreground", allow developers to select from a palette.

3. On the "game / Display" tab, for "Background colour" and "Foreground", allow developers to specify a hex colour code.

**Comment by alexwarren** [comment]
Not planning to implement any enhancements here.
