### ISSUE TITLE
"Add Script Command" combo box doesn't set focus to list box

### ISSUE THREAD

**Issue by TheOldBrick** [textadventures/quest#761]
DESCRIPTION OF PROBLEM

When a developer first clicks an "Add new script" button, an "Add Script Command" combo box appears.  The developer must click the combo box's list box to give it focus before the developer can scroll the list box with the mouse wheel.

FIX

Please, as soon as the "Add Script Command" combo box appears, the developer should be able to **IMMEDIATELY** scroll the list box without...the extra click.

**Comment by alexwarren** [comment]
Agree this is a problem but there doesn't seem to be a straightforward fix - the script command editor is a weird mixture of WPF and WinForms which seems prone to these kinds of focusing issues. Eventually the editor will be rewritten entirely, but this is a while off...
