### ISSUE TITLE
Tutorial Issues

### ISSUE THREAD

**Issue by flesh420** [textadventures/quest#773]
This isn't the first time this has happened while I'm following the tutorial.  I did everything exactly the same on this page: http://docs.textadventures.co.uk/quest/tutorial/using_timers_and_turn_scripts.html.  But when I go to see if the Turns value is updated by doing something in the game I get this: "Error running script: Error compiling expression 'player.turns + 1': ArithmeticElement: Operation 'Add' is not defined for types 'Object' and 'Int32'."

Could someone tell me what I'm doing wrong please?  There's nothing I've done different from the tutorial.

**Comment by jaynabonne** [comment]
Did you do this:

To set up our "turns" attribute, select the "player" object and go to the Attributes tab. Click the Add button next to the Attributes list at the bottom of the screen, enter the name "turns" and make this an integer.
