### ISSUE TITLE
ShowMenu() bug

### ISSUE THREAD

**Issue by WelshWillis** [textadventures/quest#775]
Hi there, I am in the process of writing/creating my 1st text game (which is brilliant btw) and while I was creating a character profile for the player to customize (I am following the example as set by http://docs.textadventures.co.uk/quest/guides/character_creation.html) using the Output - Show a Menu script, I follow the example correctly and when I run, no box appears and prints it instead and also pushes through the Wait for Key Press command.
When I looked at the code I noticed the following subtle difference

ShowMenu () creates the above error
show menu () as per the hand written code, creates the desired effect.
This is from the downloaded windows version 5.5.1

perhaps a fix from the former to the latter in the next version?

Now back to creating my adventure quest :)

**Comment by alexwarren** [comment]
Those guides are created by the community. Please submit any updates by creating a pull request.
