### ISSUE TITLE
Script :if commands

### ISSUE THREAD

**Issue by tcshaw91** [textadventures/quest#776]
So I was following the tutorial for Quest (text adventure maker). I made and object and when it went to the Verb section and selected "run a script" then selected "if", everything went fine....except there's no "then" box which the tutorial describes the program having. There's only an "else if" and "else" box.

This is only in the online version. I haven't tried downloading it.

**Comment by alexwarren** [comment]
It's the box right under the "if", with the add script button inside.

**Comment by tcshaw91** [comment]
OHHHHHHHHHH, lol i feel dumb now. thanks XD
