### ISSUE TITLE
Missing dependency in Setup

### ISSUE THREAD

**Issue by Pertex** [textadventures/quest#777]
With the new version 5.6 I can load and edit games but when I lauch a game I get the message "Error launching game: The file or assembly 'CefSharp.Core.dll' or a dependency could not be found. The module was not found."
The file is in the Q5.6 directory. When installing Quest I have to insert lokal admin name and password (what I have to do with every software).
Perhaps the DLL must be registered?

**Comment by Pertex** [comment]
After the message I can restart the game and then I get the message:
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei TextAdventures.Quest.PlayerHTML._Closure$__28._Lambda$__48()
   bei TextAdventures.Quest.PlayerHTML.ClearBuffer()
   bei TextAdventures.Quest.Player._Lambda$__3()

By the way, the button 'Copy error details to clipboard' is not working

**Comment by alexwarren** [comment]
The setup is missing a required file, which I'll add for the final release.

To get the beta working, go to
http://www.microsoft.com/en-us/download/details.aspx?id=30679 and install
VSU_4\vcredist_x86.exe.

**Comment by Pertex** [comment]
This update is installed (64bit) but it is still not working.

**Comment by alexwarren** [comment]
You need to install the 32bit (x86) version, as Quest is a 32bit app.

**Comment by Pertex** [comment]
ok, it's working

**Comment by alexwarren** [comment]
Reopening as I still need to update the Setup.
