### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by Silent-Hunter** [textadventures/quest#781]
Is Linux support planned? I'd try to port this myself, but I know nothing about Visual Basic, nor how integrated with Windows this is.

**Comment by alexwarren** [comment]
No, this is not planned for Quest. It will be supported by the follow-up, QuestKit though: https://github.com/textadventures/questkit

**Comment by Silent-Hunter** [comment]
Will QuestKit be able to launch .quest files designed for the current version of Quest? In case the one I play never updates.

**Comment by alexwarren** [comment]
No, QuestKit will generate HTML to be played in a web browser. It is not
backwards compatible with Quest.

**Comment by Silent-Hunter** [comment]
Alright, thanks!
