### ISSUE TITLE
Missing spanish localized "go in" command

### ISSUE THREAD

**Issue by creativo** [textadventures/quest#785]
There is a missing translated term in spanish "go" template command, and a couple terms aren't properly abbreviated.

File `Core/Languages/Espanol.aslx`, line: 152
```
<template templatetype="command" name="go"><![CDATA[^ir (a|al) (?<exit>.*)$|^ve (a|al) (?<exit>.*)$|^vaya (a|al) (?<exit>.*)$|^vete (a|al) (?<exit>.*)$|^vayase (a|al) (?<exit>.*)$|^váyase (a|al) (?<exit>.*)$|^ir (?<exit>.*)$|^(?<exit>norte|este|sur|oeste|noreste|noroeste|sureste|suroeste|entrar|salir|arriba|abajo|n|e|s|o|ne|no|se|so|sal|sube|baja)$]]></template>
```

Instead of:
```
<template templatetype="command" name="go"><![CDATA[^ir (a|al) (?<exit>.*)$|^ve (a|al) (?<exit>.*)$|^vaya (a|al) (?<exit>.*)$|^vete (a|al) (?<exit>.*)$|^vayase (a|al) (?<exit>.*)$|^váyase (a|al) (?<exit>.*)$|^ir (?<exit>.*)$|^(?<exit>norte|este|sur|oeste|noreste|noroeste|sureste|suroeste|entrar|salir|arriba|abajo|n|e|s|o|ne|no|se|so|sal|a|ab)$]]></template>
```

In spanish it is more common to use the term _"entrar/enter(ing)"_ a place, that _"ir adentro/go in(to)"_ a place; which it's simply frustrating to the player.

The expression do exists properly in the original english file:

```
<template name="go"><![CDATA[^go to (?<exit>.*)$|^go (?<exit>.*)$|^(?<exit>north|east|south|west|northeast|northwest|southeast|southwest|in|out|up|down|n|e|s|w|ne|nw|se|sw|o|u|d)$]]></template>
```

On the other hand, note that _"up/u"_ _"down/d"_ commands abbreviations should be replaced to _"subir/a"_ _"bajar/ab"_.

a: _**a**rriba_ abbr.
ab: _**ab**ajo_ abbr.

Commonly used in spanish games.

**Comment by alexwarren** [comment]
Could you send a pull request?

**Comment by creativo** [comment]
I've make a pull request, that should fix the compass problem. I would watch the Spanish library more closely. I have experience in software translation, so I'll be glad to help with that.

**Comment by alexwarren** [comment]
Fantastic, thanks!
