### ISSUE TITLE
Compass broken in spanish translation

### ISSUE THREAD

**Issue by Falcata** [textadventures/quest#789]
Entering in room using the compass (using "in" - "Entrar"- in compass) dont work. 
Using the link "in" - "Entrar" - works fine.

**Comment by Falcata** [comment]
The parser returns:
"I dont understand the command" - "No entiendo el comando" -

**Comment by Falcata** [comment]
Trying workaround: not using the "in/out" room definition and using the normal compass definition (N/S/E/W) instead.

**Comment by Falcata** [comment]
Ver 5.6 of Quest

**Comment by alexwarren** [comment]
Can no longer reproduce this, so this was probably fixed with the updates to Espanol.aslx in Quest 5.6.1.
