### ISSUE TITLE
Should not all timers suspend during an ASK event?

### ISSUE THREAD

**Issue by xordevoreaux** [textadventures/quest#790]
The player has lit a match. When the match is lit, it has a set number of clock ticks before the match burns out (approximately 20 seconds).

While pondering the question below, which has absolutely nothing to do with the match, the match that the player lit earlier finally burns out.  Should not all timers suspend while the player is reading a yes/no question?

> put candle in backpack
The candle may flame out if you place it in the Object: test_backpack. Place the candle there anyway?
1: Yes
2: No
The match burns out completely, leaving nothing behind.

**Comment by alexwarren** [comment]
I don't really see why they should? How is this any different to anything
else that happens in a game?

**Comment by xordevoreaux** [comment]
Things decay around the player if they don't do anything.  The player is penalized in the above scenario for "not doing anything" for taking the time to read the question.

**Comment by alexwarren** [comment]
I still don't see the difference. If you want something to happen after 20
seconds, then something will happen after 20 seconds. If the player looks
at an object, I wouldn't expect the timer to pause while they read the
object description.

If you want to pause the timer during an ask, then just add a script to do
so, and re-enable it afterwards. I don't think this would be desirable
behaviour for every game, and I don't want to clutter up the "ask" syntax
by making it an option.

**Comment by xordevoreaux** [comment]
I put a disable and enable timber before and after the ask question, the match burned out anyway, even after disabling the timer.

 I'll post a note on the forums, maybe someone can help with the code for that.

**Comment by alexwarren** [comment]
Make sure you're enabling the timer in the ask response script, so it only
fires after the player chooses something. If you just put it immediately
after the ask script, it will get immediately re-enabled before the player
responds.

**Comment by xordevoreaux** [comment]
The timer seems to be arrested, and I'm getting a scope issue, apparently, getting an error, but that's a different problem, I'll post those on the forums.
Thanks Alex.
