### ISSUE TITLE
When changing a description from Text to Script, the existing text should be preserved

### ISSUE THREAD

**Issue by ThePix** [textadventures/quest#791]
Say I have a room or item with a description written as a string, but I realise I want to have it more complicated, so it will need a script. If I change the type to Stript the existng text is lost.

Would it be possible to instead have it inserted into a msg script command? Perhaps if you click a button?

**Comment by alexwarren** [comment]
I'm not sure there's a straightforward way to incorporate this into Quest's design, but I'm planning for QuestKit to allow both text and script "actions" at the same time. This will allow you to simply add a script and leave the text where it is.
