### ISSUE TITLE
Changes to scripts are lost when using code view

### ISSUE THREAD

**Issue by F2Andy** [textadventures/quest#797]
The facility to see the code for a specific script within the GUI is great, but Quest has a habit of forgetting changes you have made if you do not toggle back to numpty-view first. It does not always do this, but one to consistently see it is to add a new verb to an object, set it to script, go to code view, type some code, then click to add a new verb. All the code you just typed in will disappear.

**Comment by alexwarren** [comment]
I've fixed the specific case you mentioned. If there are others please log those separately.
