### ISSUE TITLE
create timer does not work?

### ISSUE THREAD

**Issue by F2Andy** [textadventures/quest#800]
I tried this script:

    create timer ("testts")
    ts = GetObject("testts")
    msg ("here1")
    msg (ts)
    msg ("here2")

And got this result:

    here1
    Error running script: Object reference not set to an instance of an object.

I have no particular need for it, I was just seeing how it works, so if it was removed from Quest I would not care particularly.

**Comment by alexwarren** [comment]
A timer is not an object, so you're getting `null` when you call `GetObject`.

You can see that the timer is indeed created correctly if you look in the Quest debugger.
