### ISSUE TITLE
Exit does not work

### ISSUE THREAD

**Issue by EpicBoss39** [textadventures/quest#808]
when testing the game the exit just says 'go north' but never moves. Also when attempting to attach a lock the key does not work.

**Comment by cr0550ver** [comment]
Sorry brother, didn't quite mean to publish it yet. Though you can only advance when completing an unidentified task. I know......
Regards

Sent from Outlook




On Mon, Sep 7, 2015 at 4:02 AM -0700, "EpicBoss39" <notifications@github.com> wrote:












when testing the game the exit just says 'go north' but never moves. Also when attempting to attach a lock the key does not work.

**Comment by alexwarren** [comment]
I don't understand this, it sounds like something you've broken in your particular game, not an issue with Quest itself. If you need help please ask in the forums.
