### ISSUE TITLE
on ready fails to wait for ShowMenu

### ISSUE THREAD

**Issue by F2Andy** [textadventures/quest#810]
In theory, *on ready* should wait until all callbacks have been done, however, if fails to do that with *ShowMenu*. A simple demo is provide, paste this into the start script:

    ShowMenu ("test menu", Split("One|Two|Three", "|"), false) {
      msg (result)
    }
    on ready {
      msg ("here")
    }

The "here" message is displayed immediately, not after the ShowMenu has finished.

**Comment by alexwarren** [comment]
Unfortunately `on ready` only works for callbacks which are defined by script commands. `ShowMenu` is a function defined in the core library.

This is a known issue logged already as #668.
