### ISSUE TITLE
Harware Accellerration Text Bug

### ISSUE THREAD

**Issue by Davrial** [textadventures/quest#812]
I run an AMD based graphics card, and one of the weird things it tends to do is apply certain game-based settings to not only the visuals but the text within programs. This applies to a wide variety of programs, including such things as Paint.NET. Normally this is easily fixed by going into the program's settings and disabling Hardware Acceleration. However, Quest does not currently have that option.
Could one possibly be added, or could someone direct me to how to fix it via .config files?

Oh, and for clarification, what it does is make text and hard images rounded, which makes small images bubbly and small text difficult to read. It is also only applying to when a game is running, not the editor.

**Comment by alexwarren** [comment]
This is the first time I've heard of anything like this, and given that you experience problems in other programs as well, it's clearly a hardware or driver problem. I don't think this is something that applications should need to support overriding at the application level. There might be a compatibility setting or something you can use but I'm not going to add anything to Quest to support this case.
