### ISSUE TITLE
Recognises brackets as parts of the "ToString()" parameter

### ISSUE THREAD

**Issue by HerzogTrollhausen** [textadventures/quest#815]
Error message looks like this:
Error running script: Invalid attribute name 'id)).Land' in 'GetObject("Zelle"+ToString(Zelle.id)).Land = Land'
This was used in a function, a similar line ("GetObject("Zelle"+ToString(this.id+1))") works well.
No, it has nothing to do with the .Land at the end, it's the same error occuring than.

**Comment by alexwarren** [comment]
Can you send me an example aslx file demonstrating the issue?

**Comment by alexwarren** [comment]
Can't fix without a repro.
