### ISSUE TITLE
Volume limit for inventory counts all children not direct children

### ISSUE THREAD

**Issue by ThePix** [textadventures/quest#816]
In the DoTake function, if the inventory is limited by count, it only looks at the direct children, which is what you would expect - putting stuff in a pack saves your inventory space. However, if you limit by volume, it counts all children, so includes everything in your pack in the calculation.

**Comment by Pertex** [comment]
so what should be changed? limited by count or limited by volume? Ignoring the volume of children can be done by setting the volume to 0

**Comment by ThePix** [comment]
Limited by volume should bechanged to use GetDirectChildren, so it does not include the volume of items in containers, but does include the volume of the container and other items held. You only want the volume of children ignored when they are inside the container.

**Comment by Pertex** [comment]
Thats not the way I see it. If a container is limited by count you can carry a chest. Within this chest you can put lots of smaller objects. So if you can carry the chest you can also carry all objects within the chest. But when using volume limited containers you can perhaps carry the chest but you can not put tons of gold in it and ignore its volume.

**Comment by ThePix** [comment]
But it is the volume of the chest that is important. Say the chest has a volume of 6 and a capacity volume of 6. The player picks up some items of volume 2, three should fit in the chest, but not the fourth. So far I think we agree.
The problem is about what the player can carry. Say his carry volume is 10, he cannot pick up the chest, because the chest has three things inside it. Quest counts the volume of the chest, plus the volume of its contents, to get a total of 12.
You might say the player should not have a volume, but some writers will disagree, and putting a container inside another container is certainly done wrong.

**Comment by Pertex** [comment]
>The problem is about what the player can carry. Say his carry volume is 10, he cannot pick up the 
>chest, because the chest has three things inside it. Quest counts the volume of the chest, plus the 
>volume of its contents, to get a total of 12.
Yes, thats true but it is so intended. Lets say you can carry a chest of 50 kilo (in reality). Now you put 50 kilograms of gold in this chest, so the chest has a total volume of 100. You wouldn't be able to carry this chest any more.

**Comment by F2Andy** [comment]
Then it should be called weight (or mass) and not volume!

**Comment by Pertex** [comment]
ahhh now I understand. OK, renaming the option could be useful. I don't think it's a good idea to change the current functionality because of existing games. Would it be useful/worth to add a real volume limit? How many user will use this feature? It seems to be the first time that a user has a problem with that.

**Comment by alexwarren** [comment]
I'm happy to take a pull request for this if somebody wants to split this out into "limit by volume" and "limit by mass" features. Otherwise, closing this for now as I have no plans to change this feature myself.
