### ISSUE TITLE
changing alias of exits

### ISSUE THREAD

**Issue by Pertex** [textadventures/quest#817]
If you change the alias of an exit by typing a new alias (not choosing one from the combobox) the exit is not shown at the compass rose any more. It seems that the alias controls the display of the compass rose but it should controlled by the type of the exit

**Comment by alexwarren** [comment]
The names of the compass directions are set by

    request (SetCompassDirections, Join(game.compassdirections, ";"))

in `InitInterface`.

The UI doesn't "know" anything about types. It can only light up a compass button based on it matching the name sent to it in this request.
