### ISSUE TITLE
Eval inside an if statement causes an error

### ISSUE THREAD

**Issue by F2Andy** [textadventures/quest#820]
This works fine:
`msg (Eval ("true"))`

This generates an error:
`if (Eval ("true")) {`
`  msg("yes")`
`}`
`-> Error running script: Error compiling expression 'Eval ("true")': RootExpressionElement: Cannot convert type 'Object' to expression result of 'Boolean'`

**Comment by alexwarren** [comment]
It's a limitation of the current script runner. The return type of "Eval"
is not a boolean - it can't know what the return type is until it evaluates
the expression. It might work if you use

Eval("true") = true

though maybe.
