### ISSUE TITLE
Missing JavaScript file causes player to stall, but editor still runs

### ISSUE THREAD

**Issue by ThePix** [textadventures/quest#821]
If you have a link to a JavaScript file in your game, but that file is missing, the editor will still run the game. However, the web player justs gets stuck saying "Loading..." This leads to very confused creators!

The editor should give an error or warning if the file is missing.

**Comment by alexwarren** [comment]
I agree. Unfortunately I can't see a straightforward way of implementing this - it's not clear where and when would the warning appear and I don't want to break any games which currently work in the desktop version.

Ideally the web-based version would be as forgiving of missing JavaScript files as the desktop version. Again I can't see a straightforward way of making that happen with the current architecture of WebPlayer.

However the web version will be equally forgiving when I finish my rewrite for Quest 6, so I'll close this issue for now.
