### ISSUE TITLE
CSS Styling element reverting on save resume

### ISSUE THREAD

**Issue by OurJud** [textadventures/quest#822]
Just wondering if anyone is ever going to fix the bug with the online version of Quest, which causes the input box to reappear on the resumption of a saved game, for players who have used CSS and javascript to hide it.

On first load (correct)

![gamescreenfrstload](https://cloud.githubusercontent.com/assets/10042142/11580794/d2cbce16-9a32-11e5-8970-ee7233de76cf.jpg)

On save resume (problem)

![gamescreenresume](https://cloud.githubusercontent.com/assets/10042142/11580793/d2c94e3e-9a32-11e5-90cb-e98350f71402.jpg)

**Comment by alexwarren** [comment]
Can you add a link to your game?

**Comment by OurJud** [comment]
Certainly.
http://textadventures.co.uk/games/view/3d9aaxv3nuaxvkah3r_boq/aftermath-test

When testing to see this, key press the first couple of intro screens until you get the parser / cursor (I don't use the border around the parser field. Then come out of the game and resume. You will see the above screen shot. Type something, and the white bar you see will become the parser field with the unwanted border surrounding it.

Thanks for taking a look at this.

**Comment by OurJud** [comment]
Certainly.
http://textadventures.co.uk/games/view/3d9aaxv3nuaxvkah3r_boq/aftermath-test

When testing to see this, key press the first couple of intro screens until you get the parser / cursor (I don't use the border around the parser field. Then come out of the game and resume. You will see the above screen shot. Type something, and the white bar you see will become the parser field with the unwanted border surrounding it.

Thanks for taking a look at this.


Date: Fri, 4 Dec 2015 08:05:10 -0800

**Comment by OurJud** [comment]
NB: Alex, I think it's relevant to tell you this issue isn't with just my game. Any game in which the author has hidden the border from the parser field is affected.

**Comment by OurJud** [comment]
Hi, Alex.

Just posting to ask if you've made any progress on this?

**Comment by alexwarren** [comment]
I haven't looked at this yet, but where are you setting the CSS? There's an InitInterface function which you need to use for this kind of thing. If you put it in the game start script, that won't get run when the game reloads, by design.

**Comment by OurJud** [comment]
As far as I'm aware, the CSS block is included in the main game code. Not sure what you mean by interface, but I'll take a look and ask on the forum.

**Comment by OurJud** [comment]
Hi, Alex. I found the IntInterface in the library section, but have no idea what I need to do from there. I have JS running as a Start Script in Game, which calls the css, but don't know if it's this that I need to add to IntInterface.

**Comment by alexwarren** [comment]
Yes that would need to moved to InitUserInterface - see http://docs.textadventures.co.uk/quest/guides/modifying_the_ui__advanced_.html

**Comment by OurJud** [comment]
Ah, then I'm afraid the problem still remains, as the JS that calls the CSS has already been added to InitUserInterface.

**Comment by alexwarren** [comment]
Let's move this to the forums http://forum.textadventures.co.uk/viewtopic.php?f=10&t=5754&p=39844#p39844 - if it turns out it's actually a bug we can re-open this.

**Comment by OurJud** [comment]
http://textadventures.co.uk/user/view/9dhlnmo6huwpmnvsq_lx5w/ourjud

**Comment by alexwarren** [comment]
Fixed - command bar text formatting (background and font size) wasn't being applied after resuming a game.
