### ISSUE TITLE
Game description update not working

### ISSUE THREAD

**Issue by XanMag** [textadventures/quest#823]
I have uploaded my newest game several different times with the newer game description.  Upon publishing, it always reverts back to the old game description.  I try to 'edit this listing' under my game link and paste the new game description followed by clicking 'update'.  I always get a 'sorry, something went wrong, a problem has occurred' message.

I am perfectly okay with deleting the game entirely from the site and re-submitting an upload.  I'd like to start counters and ratings from scratch anyway.  Thanks.

**Comment by alexwarren** [comment]
Can you add a link to your game?

**Comment by XanMag** [comment]
http://textadventures.co.uk/games/view/binakb9jheqtorcg8mtazg/xanadu-the-worlds-only-hope-part-2-revenge
 


    On Friday, December 4, 2015 11:04 AM, Alex Warren <notifications@github.com> wrote:
 

 Can you add a link to your game?—

**Comment by alexwarren** [comment]
HTML is not currently supported in game descriptions. I need to update the site to handle this more elegantly instead of showing a generic error message though. If you remove the HTML tags your description update will work properly.
