### ISSUE TITLE
Game saved text is not styled

### ISSUE THREAD

**Issue by F2Andy** [textadventures/quest#824]
On-line, the text that says the game is saving and has been saved is in the default font, colour, etc. This means if the background is black it is invisible, but even in other cases it is quite jarring. All the other output text goes in its own span, with styling attached, but not this:

    <br>
    <span style="font-family:'Bubblegum Sans', Georgia, serif;color:Maroon;font-size:12pt;">The track stops at a small stone edifice, standing to the north.</span>
    <br>
    <span style="font-family:'Bubblegum Sans', Georgia, serif;color:Maroon;font-size:12pt;">You can go west or north.</span>
    <br>
    Saving game...
    <br>
    Game saved successfully.
    <br>

See also:
http://forum.textadventures.co.uk/viewtopic.php?f=10&t=5714

**Comment by alexwarren** [comment]
This text is added by JavaScript in `player.js` which doesn't have a way of knowing what the current game font style is.

For the v6 rewrite I'll look at this again - I'll add a modal progress bar or something instead of this fairly clunky text output.
