### ISSUE TITLE
"Show picture" choose file on verb doesn't work

### ISSUE THREAD

**Issue by jonscrut** [textadventures/quest#826]
Hi,

When I try to choose an image for the "show picture" script on the verb tab, the image is never chosen.

Choosing the same image on another tab, for example the Set-up tab on an object ("Look at" object description: -> Run script -> Show Picture) works just fine.

**Comment by alexwarren** [comment]
I can't reproduce this? I've tried in both the web and the desktop versions.

If you're still able to reproduce the problem, could you attach an aslx file where the problem occurs?
