### ISSUE TITLE
getCSS failing in Firefox

### ISSUE THREAD

**Issue by alexwarren** [textadventures/quest#830]
See http://textadventures.co.uk/games/view/tpyolevrh0wgdinhbugw-a/parser-test and this thread http://forum.textadventures.co.uk/viewtopic.php?f=10&t=5754&start=15

Resuming the game in Firefox gives blank output, and the console shows a security error calling get CSS.

**Comment by OurJud** [comment]
Is this simply a reminder / 'to do' list for yourself, Alex?

Keep us posted :)

**Comment by alexwarren** [comment]
It is assigned to the "Quest 5.6.3" milestone which will be the next bugfix release. It won't be forgotten :)

**Comment by OurJud** [comment]
Marvellous! Thanks for the reply.

**Comment by alexwarren** [comment]
Now checked in a fix for the getCSS exception in Firefox.

**Comment by OurJud** [comment]
Great. Thanks, Alex.
