### ISSUE TITLE
Game release dates should be when they are published, not uploaded.

### ISSUE THREAD

**Issue by ThePix** [textadventures/quest#831]
In particular, what thw web site considers latest games should be based on when the game is published, not uploaded.

See here:
http://forum.textadventures.co.uk/viewtopic.php?f=3&t=5778

**Comment by alexwarren** [comment]
If you send me a link to your game I can update the date for you in the database.

**Comment by ThePix** [comment]
Hi Alex


The last week or so, I have been seeing this, off and on, when I visit the form:

Error 522 Ray ID: 2bb3a6eaaf8b0ccb * 2016-06-30 18:24:09 UTC
Connection timed out
I try again a few minutes later and it is fine.
