### ISSUE TITLE
Dialogue boxes disappear when you open a new window on your computer!

### ISSUE THREAD

**Issue by lightwriter94** [textadventures/quest#835]
Let's say I am using Quest and open a dialogue box like the script selector or something like that opens up in a new window... then I decide to go to Firefox or some other program to do something and come back to Quest.
The window will have vanished and I will be unable to click anything in Quest because the box is invisible and in order to get it back I have to close the other program I'm using or exit Quest and it will magically reappear.

**Comment by ThePix** [comment]
I think the problem is the dialogue is behind Quest. The solution is to minimise Quest, then dismiss the dialogue. This is the nature of modal dialogues, so not something that is going to change I am afraid.
