### ISSUE TITLE
"Quest" crashes and freezes while I am using it

### ISSUE THREAD

**Issue by Marion34** [textadventures/quest#846]
Hi everyone.
I enjoy "Quest 5" a lot, it's perfect for the project I have in mind. 
I succeed in coding what I need.
My problem is, the software often freezes and crashes. It happens mostly when I open a tab with code in it (for example, a custom command with many conditions). Sometimes it keeps running after a while, but sometimes I have to shut down the software and lose my work, because it doesn't answer any more...
Is there a way to avoid those freezings ?
Thank you !

**Comment by alexwarren** [comment]
Can you attach an example aslx file that has the problem?

**Comment by Marion34** [comment]
It doesn't have the problem any more, thank you :)

2016-03-25 13:25 GMT+01:00 Alex Warren <notifications@github.com>:
