### ISSUE TITLE
Check this out

### ISSUE THREAD

**Issue by 1j01** [textadventures/quest#848]
"Check out" should be a synonym for "Examine"

**Comment by alexwarren** [comment]
Not sure I agree, is this standard in any other system? It's easy enough for a game author to add it themselves.

**Comment by 1j01** [comment]
Does it matter if it's "standard" or exists in some other system? Could "check out x" mean anything else? I suppose there could be "check out of the hotel" or just "check out". However, if those two things could be special-cased by a game author reasonably easily, I'd hold that this should be added.
