### ISSUE TITLE
Enter key does nothing in Quest desktop app

### ISSUE THREAD

**Issue by muddlemand** [textadventures/quest#851]
I've just downloaded Quest 5.6.5783.24161, as a player rather than creator (yet ;)).

First step of the game (which is A Stranger, Unregarded), I can't enter any action - nothing happens when I hit my Enter key. This isn't just extreme lagginess; as backspace does indeed delete the command I'm trying to use. It's as if my Enter key isn't functioning, but everywhere else, it is.

Surely I'm not the first person this has ever happened to? Help!

**Comment by muddlemand** [comment]
ps. Same in the game creator - when running to test, Enter does nothing. It does work in the editor. All other keys seem to work fine though the mouse pointer disappears when in the Quest window, which is inconvenient for filling in forms.

I'm using Win10 on an almost brand new laptop, wondering if this is a Win10 compatibility thing?

**Comment by muddlemand** [comment]
Solved this myself - Quest must be run as administrator. I changed this setting, using the compatibility troubleshooter, so that I don't have to bother opening it that way every time.

Online, it never saves my game although I tell it to save, and I'm logged in. Therefore the desktop app is the only way.

Does nobody reply here? Just idly wondering, y'know, since I personally am sorted now.

**Comment by alexwarren** [comment]
Sounds more likely to be a driver issue. I've not heard of anybody else having these kinds of problems and Quest works fine on Win10 for me.
