### ISSUE TITLE
Exits do not work (online editor)

### ISSUE THREAD

**Issue by F2Andy** [textadventures/quest#855]
Creating a simple exit with the online editor, and then playing the game and using the exit, generates this error:
Error running script: Error compiling expression 'HasScript(exit, "look")': Unknown object or variable 'exit'

First reported here:
http://forum.textadventures.co.uk/viewtopic.php?f=10&t=6072

May also be an issue offline, I have not updated Quest recently.

**Comment by alexwarren** [comment]
This was caused by a bad update to `English.aslx` which I reverted from the web version when it was reported. I've now undone the change to the code here on GitHub too.
