### ISSUE TITLE
Latest Source does not compile due to missing DLL references

### ISSUE THREAD

**Issue by deaii** [textadventures/quest#856]
Player.vbproj is missing references to CEFSharp dlls (although the git packages are referenced in the vbproj's target's and in packages.xml).  Adding references to the dlls in question allows the solution to build as normal.

Repro: git clone to a fresh git repository, open Quest.sln, and Ctrl+B to build.  Running Windows 10 and VS 2015 community.

**Comment by alexwarren** [comment]
No issues here. Clean checkout, Rebuild Solution in VS 2015 Professional.

Make sure you have an internet connection for the NuGet Package Restore to succeed, as that's where the CefSharp DLLs come from.
