### ISSUE TITLE
Cannot change command textfield style.

### ISSUE THREAD

**Issue by ThePix** [textadventures/quest#857]
Changes to the command textfield are ignored when done in either game.start or InitUserInterfacet. It does work in a room script however. I would guess either some is setting it back to white after game.start and InitUserInterface have both done, or the text field is only added after game.start and InitUserInterface have both done, and they fail to do anything as it just does not exist when trying to set it.

See thread.
http://forum.textadventures.co.uk/viewtopic.php?f=10&t=6256&p=42426#p42426

**Comment by alexwarren** [comment]
If you can you attach a sample that demonstrates the problem, I'll reopen this and take a look.

**Comment by ThePix** [comment]
Here is a sample game. It has a custom command, RED, which will change the background of the textfield, while `game.start` and `InitUserInterface` fail to do so.
```
<!--Saved by Quest 5.6.5783.24153-->
<asl version="550">
  <include ref="English.aslx" />
  <include ref="Core.aslx" />
  <game name="textfield">
    <gameid>dd75373d-1526-4fa6-8bc8-c2953f3d6675</gameid>
    <version>1.0</version>
    <firstpublished>2016</firstpublished>
    <start type="script">
      JS.eval ("$('#txtCommand').css('background-color', 'red')")
    </start>
  </game>
  <object name="room">
    <inherit name="editor_room" />
    <object name="player">
      <inherit name="editor_object" />
      <inherit name="editor_player" />
    </object>
  </object>
  <command name="red">
    <pattern>red</pattern>
    <script>
      JS.eval ("$('#txtCommand').css('background-color', 'red')")
    </script>
  </command>
  <function name="InitUserInterface">
    JS.eval ("$('#txtCommand').css('background-color', 'red')")
  </function>
</asl>
```
