### ISSUE TITLE
Playing games does not work, and crash on close

### ISSUE THREAD

**Issue by SomeGreenGoo** [textadventures/quest#862]
When I try playing a game (Any game) I can't input into the command bar (No text appears) or otherwise interact (For hyperlinks the menu shows up, but no response to choosing an action). The same is true for the compass and inventory panes. When I close the program after playing a game I get a crash with the following information:

> Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	Quest.exe
  Application Version:	5.6.5783.24161
  Application Timestamp:	563612c2
  Fault Module Name:	clr.dll
  Fault Module Version:	4.0.30319.34209
  Fault Module Timestamp:	5348961e
  Exception Code:	c00000fd
  Exception Offset:	004226a2
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1044
  Additional Information 1:	c955
  Additional Information 2:	c9551dc02ca6eedbae0a1df9618a92f2
  Additional Information 3:	c9a4
  Additional Information 4:	c9a4e95e14eade87ffbd77cce059f1bf

For one of the games I tested the debug log contained the following message:

> [0528/235936:WARNING:message_in_transit_queue.cc(18)] Destroying nonempty message queue

I tried both "Whitefield Academy of Witchcraft" and "The lunastone" the issue is the same.

I've tried reinstalling the program and restarting my computer, the issue persists.

Windows 7, quest version 5.6.2

**Comment by alexwarren** [comment]
Unable to reproduce this
