### ISSUE TITLE
Setting an object attribute fails if it is set in its type

### ISSUE THREAD

**Issue by ThePix** [textadventures/quest#864]
If you have an attribute set to an object in your type, it seems to be impossible to change the value in objects using that type.

Attached is an example game to illustrate. The SomeType type has two attributes set, an object, linkedto, and an integer, intvalue. The object my_object is of that type.

The start script tries to change the two attributes. It can change the integer, but not the object.

[setting_null.txt](https://github.com/textadventures/quest/files/326582/setting_null.txt)

**Comment by jaynabonne** [comment]
Setting an attribute to null removes it from the object. It does not assign a null value. When the attribute is removed from the object, the value from the type then becomes visible. You would see the same behavior with the int attribute if you also set it to null. 
I think I had posted about this interesting behavior a while ago. :)

**Comment by jaynabonne** [comment]
If you run the code without setting player to the attribute and then look in the debugger, you'll see that it has reverted to using the type value.

**Comment by alexwarren** [comment]
This would be a breaking change so I'll look into it for v6.0.

**Comment by ThePix** [comment]
This is just the way it is, so I am closing.
