### ISSUE TITLE
Hiding the save button stops all the game output getting saved

### ISSUE THREAD

**Issue by ThePix** [textadventures/quest#865]
The web player Save button can be hidden with either of these:

```
JS.eval ("$('#cmdSave').css('display', 'none');")
JS.eval ("$('#controlButtons').css('display', 'none');")
```

The game can still be saved, for example if the player types SAVE, but I was surprised to find that the game output does not get saved. The game state is saved, but not the text that has been generated during play.

I confirmed this by:

- Looking at the HTML source and establishing the text was not there, rather than merely hidden
- Putting a one second delay on the above code, so the button is present when the game loaded, and the text was still not there
- Creating a hide command that hides the save button, and confirming text is there for saves before the command is used, but not after; when reloaded the button reappears and text from that point on does get saved

I thought if I showed the button, waited a second before saving, then waited another second before hidding the button that might work, but no. Changing the visibility to hidden does the same thing.

I have no idea why it does this. Is it be design? It does offer a way to control what gets saved; if an author does not want the text saved, here is a possible solution.

**Comment by ThePix** [comment]
Kind of related, it would be good if authors could choose whether the entire text was saved, none of it, or the last N blocks, say with an attribute on the game object.

**Comment by alexwarren** [comment]
Looking at the code, it's not to do with whether the button is *visible* or not, but actually whether it was *clicked* or not.

The save button calls a `saveGame` function in `WebPlayer\player.js` which submits the contents of `#divOutput` along with the request to save the game. If the player *types* `SAVE` instead, this step doesn't happen.

The fix would be for typing `SAVE` to initiate some kind of request which the JS client could respond to with the contents of the `div`.

That doesn't sound too easy to implement, and as I'm rewriting the player for Quest 6.0 it's not something I plan to add to the v5 WebPlayer.

I also don't think that adding author control over how much text is saved is valuable? Ideally, saving the same has *no* effect, it just means you restore the state to exactly how it was before.
