### ISSUE TITLE
Improved compass rose

### ISSUE THREAD

**Issue by ThePix** [textadventures/quest#866]
The compass rose would be better if:
1. It had extra buttons. A look button in the centre is an obvious addition, but how about wait and help under down and out?
2. It was above the item lists; when below them it moves up and down the page, depending on how many items are in the room

See here:
http://forum.textadventures.co.uk/viewtopic.php?f=18&t=6456

**Comment by alexwarren** [comment]
I agree that having the Compass at the top would be a nice default. I'll add this to the list for v6.0.

Not so sure about the other suggestions though - adding look, wait and help buttons turns the entire Compass area into a grid, and you lose the visual distinction between the compass directions in the first three columns and the other two columns of buttons.

**Comment by ThePix** [comment]
Quest 5.7 has an option to put the compass at the top. I will follow Alex here and agree the compass should look like a compass.
