### ISSUE TITLE
error message on object drag and drop in object tree

### ISSUE THREAD

**Issue by bergedorfcacher** [textadventures/quest#867]
I'm getting this always when I use drag and drop there. The following message is displayed:
Sorry, an error has occured is Quest.
System.Exception: Starting transaction when previous transaction not finished
   bei TextAdventures.Quest.UndoLogger.StartTransaction(String command)
   bei TextAdventures.Quest.EditableScripts.set_Code(String value)
   bei TextAdventures.Quest.EditorControls.ScriptEditorControl.Save()
   bei TextAdventures.Quest.EditorControls.MultiControl.Save()
   bei TextAdventures.Quest.EditorControls.WFMultiControl.Save()
   bei TextAdventures.Quest.EditorControls.WFAttributesControl.Save()
   bei TextAdventures.Quest.EditorControls.VerbsControl.Save()
   bei TextAdventures.Quest.EditorControls.ElementEditor.Save()
   bei TextAdventures.Quest.WPFElementEditor.SaveData()
   bei TextAdventures.Quest.Editor.ShowEditor(String key)
   bei TextAdventures.Quest.Editor.ctlTree_SelectionChanged(String key)
   bei TextAdventures.Quest.EditorControls.WFEditorTree.ChangeSelection(String key)
   bei TextAdventures.Quest.EditorControls.WFEditorTree.SelectCurrentTreeViewItem()
   bei TextAdventures.Quest.EditorControls.WFEditorTree.ctlTreeView_AfterSelect(Object sender, TreeViewEventArgs e)
   bei System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   bei System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   bei System.Windows.Forms.TreeView.WmNotify(Message& m)
   bei System.Windows.Forms.TreeView.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

This is on Windows 10.

After clicking away the message there are no problems whatsoever. Even the drag and drop action is executed correctly.

**Comment by alexwarren** [comment]
This kind of error only occurs after a previous operation failed, so you would probably have seen a different error message before this one. If you can consistently reproduce the problem, please let me know the full steps and all error messages you see, and I'll reopen this and take a look.
