### ISSUE TITLE
Disabling DROP should also disable putting the object in a container

### ISSUE THREAD

**Issue by ThePix** [textadventures/quest#868]
You can untick the "Drop" option for an object, stopping the player from dropping the object. Except, it does not stop it. All the player has to do to get rid of it is put the object in a container.

The PUT X IN Y command should be modified to prevent undroppable objects getting put in there.

**Comment by alexwarren** [comment]
Hmm, maybe. Putting is a different thing to dropping.

I don't plan to make this change myself but I'd be happy to look at pull request if anyone wants to implement this. I'd want to make it part of a point release (e.g. v5.7 or more likely v6.0 as I don't think there will be a v5.7) as it would be a breaking change.

**Comment by Pertex** [comment]
is this a good idea? Perhaps the player is carrying a knife.  I don't want him to drop the knife but I want him to put it into a knife block.

**Comment by alexwarren** [comment]
Good point. This would definitely need to be configurable. And right now we don't offer any way of restricting any kind of `put`, as far as I know. So it's a bigger overall design question than just this specific case.

**Comment by ThePix** [comment]
I appreciate it is technically a breaking change, but I think it more likely games already assume an item cannot be dropped by putting it in a container, and it would correct more games than it would break. I think the expected behaviour of unticking droppable is that the object stays in the player inventory, and not that it cannot be dropped but can be put in _any_ container, carried or not.

I will look at doing a pull request. The code change is trivial, but I have struggled to use GitHub in the past.

Pertex you are talking about a very specific example. Do you want the player to be able to put the knife in any other object to drop it? I would guess not. In either alternative, you would need to code specfically for the knife in the block. It can be configured through a drop script already.

At the very least the GUI should be modified to make clear what the behaviour is.

**Comment by ThePix** [comment]
The background to this request is this thread, which also has the code change required for what I would consider the proper behaviour in the fourth post.

http://textadventures.co.uk/forum/quest/topic/x7b3sz_qd065eyxoucodyg/undroppable-object-handling

**Comment by Pertex** [comment]
Putting is something different then drop (for me). I am often using inroom description and then you can get problems with dropped items. But items in container dont make problems. 
Another situation you should consider is that the player is carrying a backpack item in his inventory and wants to put his items it it. Yes, you can do this by script but lots of user are not familiar with scripting.
I dont say that we should not have this change of drop but it should not be default but a feature
