### ISSUE TITLE
Failed to download games list

### ISSUE THREAD

**Issue by richardbutte** [textadventures/quest#869]
Windows 10, 64-bit
Quest build 5.6.5783.24161

`'http' is an unexpected token. Expecting white space. Line 811, position 42.`

**Comment by alexwarren** [comment]
Probably a temporary server or network issue, it's working at the moment.

**Comment by richardbutte** [comment]
Well, no. It's been happening for weeks (and in fact still is). I suppose it could be something on my end, though I haven't a clue what.
![untitled](https://cloud.githubusercontent.com/assets/11743868/17687922/2fdbda1c-633f-11e6-8356-d1d98cca843c.png)

**Comment by alexwarren** [comment]
What happens if you visit this URL in Internet Explorer? http://www.textadventures.co.uk/gamesxml.php?maxasl=550
