### ISSUE TITLE
"play sound" command hides the command bar

### ISSUE THREAD

**Issue by ThePix** [textadventures/quest#872]
From here:
http://textadventures.co.uk/forum/quest/topic/2xfxi6hvfeim0wcv09kukq/input-bar-or-command-bar-vanishes-after-call-function-loop

> I went through everything it'd possibly be waiting for, and found it was an audio file. If the "Wait for sound to finish before continuing" drop down is set to "no" it works (but of course the sound plays up to 8 seconds after the fact, annoying.) When set to "yes" it does indeed wait for the sound to finish before the call function pops the question again, but sans input bar. It's a 2 second .wav file, which is bigger than any of the other sounds I use in the game. I think it's just too much for the GUI - could be my system as well.
> 
> Think it's a "bug"? Can I manually correct the script? It seems correct - just goes from false, false to true, false. I played around with it but wasn't able to change anything without causing a system error.

**Comment by alexwarren** [comment]
Attach a repro please?

**Comment by ThePix** [comment]
The guy who reported this has not been seen for months, and I cannot reproduce, so I am closing this.
