### ISSUE TITLE
Tutorial: Saying Command doesn't work.

### ISSUE THREAD

**Issue by meadowlark73** [textadventures/quest#873]
I'm brand new to using Quest to create text adventures and have been working my way through the tutorial. I am currently on the Custom Commands section, the part at the bottom: "ADDITIONAL EXAMPLE - Quest can handle text and objects in the same command. Here the say command is extended to allow the player to specify who she is talking to."

I have added the command "saying" exactly as shown in the example and it doesn't work in the game. I've also tried entering the actual code exactly as shown in Code View and that doesn't work either. 

This is what I get when I run the game:

> You are in a room.
> You can see a troll and a bob.
> 
> say hi to troll
> Error running script: Error compiling expression '"You say: " +text_talk / Print "The troll grunts but    otherwise ignores you."': Unknown object or variable 'Print'

I don't understand why it's not working. Is this a bug? Am I doing something wrong? Please help.

Here is exactly how I am entering the data into the Quest Game Creator program:

- Commands - Command pattern: **say #text_talk# to #object_one#** - Name: **saying**
- Script - Switch... - Object - **object_one**
- Cases - Add - Key: **troll** - Script: Print expression **"You say: " +text_talk / Print "The troll grunts but otherwise ignores you."**  
- Cases - Add  - Key: **bob** - Script: Print expression **"You say: " +text_talk / Print "Bob smiles back at you."**

This is what shows up in the Code View box for what I entered above: 

```
switch (object_one) {
  case (troll) {
    msg ("You say: " +text_talk / Print "The troll grunts but otherwise ignores you.")
  }
  case (bob) {
    msg ("You say: " +text_talk / Print "Bob smiles back at you.")
  }
}
```

When I change that to the code shown in the tutorial, the game won't load at all:

```
<command name="saying">
    <pattern>say #text_talk# to #object_one#</pattern>
    <script>
      switch (object_one) {
        case (troll) {
          msg ("You say: " + text_talk)
          msg ("The troll grunts but otherwise ignores you.")
        }
        case (bob) {
          msg ("You say: " + text_talk)
          msg ("Bob smiles back at you.")
        }
        default {
          msg ("You say: " + text_talk + " but the " + object_one.name + " says nothing, possible because, you know, it cannot speak.")
        }
      }
    </script>
    <unresolved>Say that to who?</unresolved>
  </command>
```

**Comment by meadowlark73** [comment]
Ok, I did finally get it to work by changing the code in the Code View box to this:
```
switch (object_one) {
  case (troll) {
    msg ("You say: " +text_talk)
    msg ("The troll grunts but otherwise ignores you.")
  }
  case (bob) {
    msg ("You say: " +text_talk)
    msg ("Bob smiles back at you.")
  }
}
```

**Comment by alexwarren** [comment]
Looks like those are *two lines* of scripts in the box.
