### ISSUE TITLE
Save game folder on own server

### ISSUE THREAD

**Issue by svirusxxx** [textadventures/quest#875]
Hi,
I have problem with "save" commnad.
I set in  WebPlayerSettings.default.xml GameSaveFolder but whe I type command I see:
```
Saving game...
Failed to save game: You are not logged in. Please log in at textadventures.co.uk and try again.
```

**Comment by alexwarren** [comment]
You will need to write some custom code if you want to enable saving. The code that is in WebPlayer requires the user to be logged in at textadventures.co.uk. If you want to handle saving, you'd need to set up somewhere for the save game data to be stored, implement an API to access it, then plug WebPlayer into that.
