### ISSUE TITLE
Text Adventures Clicking Error

### ISSUE THREAD

**Issue by EricStripe** [textadventures/quest#877]
Recently I've been unable to interact with any of the commands or links on Quest's downloadable version. Whenever I click, or type a command, I get no response from the program, only usually an orange outline around what I was attempting to use. At first I thought it was the game I was on, but, I downloaded a few more and was met with the same issue.

**Comment by JoaoGFarias** [comment]
I think if you could describe better your environment, the bug could be easily spotted.

OS
Quest version
Games which caused the error

**Comment by ThePix** [comment]
If we hear no more on this, I will close it.

**Comment by ThePix** [comment]
Heard no more, so closing
