### ISSUE TITLE
Invalid XML :  Das Stammelement ist nicht vorhanden.

### ISSUE THREAD

**Issue by Stesspela** [textadventures/quest#878]
Help, after i try starting my file again, i alwals get this message and not even can work with me file.
This mean all my work is lost?

Also get this debug warning: [1025/185019:WARNING:message_in_transit_queue.cc(18)] Destroying nonempty message queue
[1025/210328:WARNING:message_in_transit_queue.cc(18)] Destroying nonempty message queue
[1025/210331:WARNING:message_in_transit_queue.cc(18)] Destroying nonempty message queue

... but because i not even can edit my file i can't do anything against ist:(

**Comment by ThePix** [comment]
If we hear no more on this, I will close.

**Comment by ThePix** [comment]
Heard no more, so closing
