### ISSUE TITLE
Error at the end of installation and whenever save is created

### ISSUE THREAD

**Issue by OKTARGrull** [textadventures/quest#879]
Hello,

I have just installed and launch Quest and it says me that an error is occured in Quest. It shows me those error details :

"System.Reflection.TargetInvocationException: Une exception a été levée par la cible d'un appel. ---> System.UnauthorizedAccessException: L'accès au chemin d'accès 'C:\Users\clment\Documents\Quest Games\Downloaded Games' est refusé.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   à System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   à System.IO.Directory.CreateDirectory(String path)
   à GameBrowser.GameList.CreateListElements(List`1 list)
   à GameBrowser.OnlineGames.PopulateGameList(String category, GameList gameListCtl)
   à GameBrowser.PlayBrowser.PopulateGames(String category)
   à GameBrowser.PlayBrowser.ctlBrowseFilter_CategoryChanged(String category)
   à GameBrowser.BrowseFilter.lstCategories_SelectionChanged(Object sender, SelectionChangedEventArgs e)
   à System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   à System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   à System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   à System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   à System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   à System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   à System.Windows.Controls.ComboBox.OnSelectionChanged(SelectionChangedEventArgs e)
   à System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(List`1 unselectedInfos, List`1 selectedInfos)
   à System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   à System.Windows.Controls.Primitives.Selector.SelectionChanger.SelectJustThisItem(ItemInfo info, Boolean assumeInItemsCollection)
   à System.Windows.Controls.Primitives.Selector.OnSelectedIndexChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   à System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   à System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   à System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   à System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   à System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   à System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   à GameBrowser.BrowseFilter.Populate(String[] cats)
   à GameBrowser.PlayBrowser.PopulateCategories()
   à GameBrowser.PlayBrowser._Lambda$__24-0()
   --- Fin de la trace de la pile d'exception interne ---
   à System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   à System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   à System.Delegate.DynamicInvokeImpl(Object[] args)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)"

Can you help me ? Thank you and have a nice day. :)

**Comment by ThePix** [comment]
I am going to close this as I think it is an issue with the users game. This is better posted on the forum where it will get addressed rather more quickly!
