### ISSUE TITLE
Online resume not reading CSS

### ISSUE THREAD

**Issue by OurJud** [textadventures/quest#880]
A couple of years ago I had a long-going discussion with a couple of forum member, including yourself (Alex), concerning the online bug which meant that certain CSS rules were not being triggered on resume of a saved online game.

You acknowledged the bug and suggested I create a Github ticket. I did this and several several months later received an email to say it had now been fixed.

I'm now considering having another attempt at making a small, traditional TA in Quest, but wanted to check the save/resume issue before I put any work in, and find that nothing has changed. I hide the border and background for the input box in my games, but on resume of a save the CSS isn't being read and the input box border pops up in a glaring white.

Before (from first load):
![aftermath_before](https://cloud.githubusercontent.com/assets/10042142/20677914/ae7504e4-b58c-11e6-9dc7-41485742b6e9.jpg)

After (on Resume of save):
![aftermath_after](https://cloud.githubusercontent.com/assets/10042142/20677936/c75a2174-b58c-11e6-9c37-42afb56cac8a.jpg)

**Comment by OurJud** [comment]
The code I'm using in InitUserInterface:
`JS.setCommandBarStyle (GetCurrentTextFormat("") + ";border:" + game.defaultbackground)
JS.eval ("$('#status').hide();")
JS.SetBackgroundCol ("black")
JS.eval ("$('#txtCommandDiv').prepend('&gt;&nbsp;')")
JS.OutputTextNoBr (game.css)
OutputTextNoBr (game.css)
request (SetInterfaceString, "TypeHereLabel=")
if (GetBoolean(game, "inprogress")) {
}
else {
  game.inprogress = true
}
`
And the link to the game where the error can be reproduced (start game, type 'save', close game then choose 'Resume' when you access the game again): 
[http://textadventures.co.uk/games/view/fnn_yl1r_ui81gcnnqrrvq/aftermath](url)

**Comment by ThePix** [comment]
Hopefully the new options in Quest 5.7 will make this obsolete.
