### ISSUE TITLE
Cannot play two sounds simultaneously 

### ISSUE THREAD

**Issue by OurJud** [textadventures/quest#881]
Not sure if this is a bug or not, but I cannot get two sounds to play simultaneously. I have a track at the start of the game set to loop, but any single sounds which are triggered after this stop the looped track.

**Comment by Pertex** [comment]
it's not possible to do this with Quest commands at the moment but you can insert some html code into your game using the HTML5-tag <audio> to play sounds simultaneously

**Comment by OurJud** [comment]
Ah, thank you. Good to know there's a workaround at least.

**Comment by ThePix** [comment]
I am closing this as it is now covered in the docs
http://docs.textadventures.co.uk/quest/adding_sounds.html
