### ISSUE TITLE
unknown error appearing..

### ISSUE THREAD

**Issue by KnoxKang** [textadventures/quest#882]
for some reason, after i upgrade my quest to quest 5 error comes up and i'm currently unable to use any of my game file, save files. 

error code as follows

System.InvalidOperationException: An error occurred while creating the form. For more information, see Exception.InnerException. Error: An exception was thrown in the constructor call for the type 'GameBrowser.PlayBrowser' that matches the specified binding constraint. ---> System.Windows.Markup.XamlParseException: An exception was thrown in the constructor call for the type 'GameBrowser.PlayBrowser' that matches the specified binding constraint. ---> System.ArgumentException: An item with the same key has already been added.
   Location: System.ThrowHelper.ThrowArgumentException (ExceptionResource resource)
   Location: System.Collections.Generic.Dictionary`2.Insert (TKey key, TValue value, Boolean add)
   Location: System.Collections.ObjectModel.KeyedCollection`2.AddKey (TKey key, TItem item)
   Location: System.Collections.ObjectModel.KeyedCollection`2.InsertItem (Int32 index, TItem item)
   Location: System.Collections.ObjectModel.Collection`1.Add (T item)
   Location: GameBrowser.RecentItems.LoadRecentList ()
   Location: GameBrowser.RecentItems..ctor (String listName)
   Location: GameBrowser.PlayBrowser..ctor ()
   --- end of internal exception stack trace ---
   Location: System.Windows.Markup.WpfXamlLoader.Load (XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   Location: System.Windows.Markup.WpfXamlLoader.LoadBaml (XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   Location: System.Windows.Markup.XamlReader.LoadBaml (Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   Location: System.Windows.Application.LoadComponent (Object component, Uri resourceLocator)
   Location: GameBrowser.Launcher.InitializeComponent ()
   Location: GameBrowser.Launcher..ctor ()
   Location: TextAdventures.Quest.Main.InitializeComponent ()
   Location: TextAdventures.Quest.Main..ctor ()
   --- end of internal exception stack trace ---
   Location: TextAdventures.Quest.My.MyProject.MyForms.Create__Instance __ [T] (T Instance)
   Location: TextAdventures.Quest.My.MyApplication.OnCreateMainForm ()
   Location: Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun ()
   Location: Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel ()

**Comment by assassin604** [comment]
i have the same error ? but no ones helped me yet either...  good luck with youres though if you figure it out plz let me know ty

**Comment by Pertex** [comment]
see issue ##885

**Comment by ThePix** [comment]
This just needs the solution needs to be in the documentation.
