### ISSUE TITLE
Transfer game from one computer to another

### ISSUE THREAD

**Issue by STRATEGANJ** [textadventures/quest#884]
While I don't use Quest hardcore style, I really enjoy using Quest. I've been working on a game on one of my computers and don't know how to transfer that game to my laptop. Is this already a thing and I just don't know how to do it, or is it not a thing? If it's not a thing, will you be adding this feature?

**Comment by Pertex** [comment]
look in the Documents folder and you will find a Quest Games folder. Within this you will find your game. Copy this game folder with all of its files to your laptop (same structure) . Now start Quest on you laptop and load the game file from this folder.
I am sure there will be no feature doing this for you in the future.

**Comment by ThePix** [comment]
I am closing this; as Pertex says, it is never going to be a feature.
