### ISSUE TITLE
The slow scrolling down upon game loading. 

### ISSUE THREAD

**Issue by alexandretorres** [textadventures/quest#893]
When loading a game in the quest client, the scroll function goes really slow, and it overrides the user scroll, so the player can't do anything except to wait for several minutes. Also, If I scroll the game up and type some command, the slow scroll happens again. This is really annoying. it has a forum entry about this problem (https://textadventures.co.uk/forum/quest/topic/6433/the-slow-scrolling-down-upon-game-loading). A javascript workaround would be appreciated. Also, the "clear before save" solution is not acceptable for every game.

Digging a bit on it, I found that the problem MAY be related to checkInView timer declared at playcore.js
That is the best I can do right now. Also, I can override scrollToEnd to stop scrolling, but did not figure it all yet.

**Comment by alexandretorres** [comment]
Ok, here is my HACK code. It is an workaround that sets a maximum duration for the animation (in this case, two seconds)

    function scrollToEnd() {
    var scrollTo = _animateScroll ? beginningOfCurrentTurnScrollPosition - 50 - $("#gamePanelSpacer").height() : $(document).height();
    var currentScrollTop = Math.max($("body").scrollTop(), $("html").scrollTop());
    if (scrollTo > currentScrollTop) {
        var maxScrollTop = $(document).height() - $(window).height();
        if (scrollTo > maxScrollTop) scrollTo = maxScrollTop;
        var distance = scrollTo - currentScrollTop;
        var duration = _animateScroll ? distance / 0.4 : 1;
	// here is the hack	
        if (duration>2000)
	    duration=2000
        $("body,html").stop().animate({ scrollTop: scrollTo }, duration, "easeInOutCubic");
    }
    $("#txtCommand").focus();
}

**Comment by ThePix** [comment]
I have added the "hack" to Quest 5.7, as it looks reasonable.
