### ISSUE TITLE
Escape From The Forbidden City

### ISSUE THREAD

**Issue by Vorkenstein** [textadventures/quest#894]
Escape From The Forbidden City

When you first exit the cell and turn left you are at a corner(#1).
North leads to park(#1).
When you first exit the cell and turn right you are at a junction.
Go north to shops.
Go north to crossroad.
Go left to corner(#2)
North leads to park(#2).
South leads to corner(#1), then north leads to park(#1).

Suggested fix:
Have corner(#1) go north in an alley or street to corner(#2)
which then goes to the park.

**Comment by ThePix** [comment]
I am closing this as it is specific to a game. Vorkenstein, I suggest you post this in the comments for the specific game so the game author will (hopefully) see it.
