### ISSUE TITLE
Command bar unresponsive

### ISSUE THREAD

**Issue by Jesseman1** [textadventures/quest#895]
I just downloaded Quest yesterday, but when I tried to play a game, the command bar wouldn't work; entering a command and pressing enter didn't do anything. I figured the game was broken, but then I tried to play a different game and the same thing happened, not even click-commands would work. Has anyone else run into this problem or know how to solve it?

**Comment by ThePix** [comment]
I am going to close this as I think it is an issue with the users game. This is better posted on the forum where it will get addressed rather more quickly!
