### ISSUE TITLE
"You can't control"

### ISSUE THREAD

**Issue by benjaminpants** [textadventures/quest#898]
I am making a robot with a remote control. But when I create the verb no matter what is in the verb it always says "You can't control"
I BEEN TRYING TO FIX IT FOR SUCH A LONG TIME!!

**Comment by ThePix** [comment]
This is probably an issue with your game, rather than Quest itself. If you are still having a problem, I suggest posting on the forum ( which get much faster responses!). Post as much of the code as you can, and also mention if you are using the web version or desktop.
