### ISSUE TITLE
Game won't start

### ISSUE THREAD

**Issue by roflmaopcs** [textadventures/quest#900]
I'm trying to start quest and it won't start any games. I've tried several of them, I tried reinstalling quest and downloading the games, but I keep getting the following error:

System.NullReferenceException: Object reference not set to an instance of an object.
   at TextAdventures.Quest.PlayerHTML._Closure$__84-0._Lambda$__1()
   at TextAdventures.Quest.PlayerHTML.ClearBuffer()
   at TextAdventures.Quest.Player._Lambda$__122-0()

**Comment by ThePix** [comment]
I am going to close this as I think it is an issue with the users game. This is better posted on the forum where it will get addressed rather more quickly!

**Comment by roflmaopcs** [comment]
I said I tried a variety of different games, but forget it, I'm just using
an older version
