### ISSUE TITLE
After a ShowMenu is done, a large gaps is left

### ISSUE THREAD

**Issue by ThePix** [textadventures/quest#904]
Noted by Dcoder

When a list of options for ShowMenu is removed (say the player has selected something), a large blank space is left between the remaining text and the command bar.

This is because Quest has set a min-height for the divOutput (in addText in playercore.js), and a simple fix would be to remove that line, but I assume it is there for a reason.

For 5.8

**Comment by KVonGit** [comment]
I just built Quest again to check this out, and it is NICE, Pix!

👍
