### ISSUE TITLE
Missing ObjectCannotBeStored template

### ISSUE THREAD

**Issue by KVonGit** [textadventures/quest#909]
I have an object (lamp) set up so that it cannot be dropped.

I also have a container (pouch).

---
\> put lamp in pouch
Error running script: Error evaluating expression 'DynamicTemplate("ObjectCannotBeStored", object1)': No template named 'ObjectCannotBeStored'

---

Creating a Dynamic Template with the appropriate name fixed it easily.

---
**ObjectCannotBeStored**

``` xml
  <dynamictemplate name="ObjectCannotBeStored">"You can't put " + GetDisplayName(object) + " in there."</dynamictemplate>```

**Comment by ThePix** [comment]
Fixed for Quest 5.7.2
