### ISSUE TITLE
Restrict all

### ISSUE THREAD

**Issue by ThePix** [textadventures/quest#914]
Consider have eg GET ALL not include NPCs. Are there other examples?

**Comment by KVonGit** [comment]
There are so many different possible scenarios...

I've been creating a ```not_all``` Boolean attribute so it's easy to handle objects individually (like taking and dropping), with the attribute set to false by default.

After adding the IF... in the TAKE command, I also realized there was no message when there was nothing to take by default.  So I tacked on a good, old-fashioned 'There is no 'all' to take.' after the ELSE...

**Comment by ThePix** [comment]
Reorganised how ALL is done, and set GET ALL to ignore NPCs.
