### ISSUE TITLE
setCss is not defined

### ISSUE THREAD

**Issue by tass23** [textadventures/quest#915]
I didn't see anyone else that brought this up anywhere, and I spent a few days searching the web for the answer. So here is the situation:
Downloaded Quest 5.7.1
Downloaded QuestJS latest
Game exports, and compiles without issue.
When the index.html file opens, you only see the menu bar at the top of the screen and the command bar. Everything else is empty. When you use Code Inspector (Chrome or Firefox), I see an error about setCss is not defined. When I go and look at the code in game.js it is always related to the new additions and changes to the Interface. If you use a hex code for color, color name, don't use that feature at all, it is the same issue.

How or what did I miss?
(Note: I realize there is a new Quest version being developed that includes functionality so that an export isn't needed. However, if this is an easy fix, it would allow people to use the latest QuestJS with Quest 5.7.1, unless I'm the only one that has run across this.)

**Comment by ThePix** [comment]
QuestJS was not updated with the new JavaScript that Quest uses in playercore.js (and for upcoming 5.7.2 grid.js). The official position is that QuestJS is no longer maintained, and it is not something I have looked at at all. I will leave this open for now as it might get updated, but as of now I do not even know what file to edit.

If anyone else wants to look further...

**Comment by KVonGit** [comment]
I'll see what I can get out of it.

Will 5.7.2 have another JS change?  Or will it be the same file I have access to now?

**Comment by KVonGit** [comment]
This seems to fix it.

There was a game.js file in the directory the output files are saved to.  I added a few functions (copied directly from my Quest 5 directory).

setCss
createNewDiv
getCurrentDiv
setCurrentDiv
getDivCount

Replace your file with this one, and see what happens, please.

https://gist.github.com/KVonGit/05980d7595cfd18487ec28663a872b66

**Comment by tass23** [comment]
Nice work! Thanks very much! :)
That seems to have fixed the hangup I was having. I would say push that commit for anyone that wants to use the latest QuestJS. That really does appear to be the only problem with it.
