### ISSUE TITLE
Russian game not working in web version

### ISSUE THREAD

**Issue by zella** [textadventures/quest#916]
I create russian game(tried only web version):

![2017-09-05 16 46 39](https://user-images.githubusercontent.com/3839393/30055483-d42f3d94-9259-11e7-91a5-0e39abb08446.png)

Without any changes tap "Play" and get error

![2017-09-05 16 47 51](https://user-images.githubusercontent.com/3839393/30055530-f9fd6c1c-9259-11e7-8085-78c53898e45e.png)

**Comment by ThePix** [comment]
Fixed for Quest 5.7.2

**Comment by tszyan** [comment]
It doesn't work on http://textadventures.co.uk/

**Comment by ThePix** [comment]
It will on the next update, which I hope will be in a few weeks.

**Comment by tszyan** [comment]
Thank you. I'll be waiting.
Yet it is critical. No game could be created during this weeks using one of the "supported" languages.
No windows distribution for 5.7.2 too.

**Comment by GarwelGarwel** [comment]
One way to fix it is to add `remove` template manually.

**Comment by ThePix** [comment]
The update took longer than I hoped, but is now in beta, so should be soon. I hope.

**Comment by GarwelGarwel** [comment]
Sounds good! Unfortunately, there are some other issues with Russian localization that I couldn't so easily resolve. For instance, non-directional exits don't seem to work: you get either "_Error running script: Error compiling expression 'object': Unknown object or variable 'object'_" error or just unrecognizable command when you try to actually go there.

**Comment by Tonvengo** [comment]
@GarwelGarwel Have you found a way to fix non-directional exits with Russian localization? :)
