### ISSUE TITLE
No divCount in saved game after clearing the screen

### ISSUE THREAD

**Issue by KVonGit** [textadventures/quest#917]
When you clear the screen, then save a game, the load that game, ClearMenu does not work.

I played around with everything and adding ```JS.getDivCount()``` to the initialisation script fixes it.

---
See this thread:

http://textadventures.co.uk/forum/quest/topic/6j-wzgnus0urepk6bksura/what-can-break-displaying-menus#cebf0fcd-9060-4e6d-a714-03e33549d05e

---
I tried and tried to find some sort of default initialisation script, but to no avail.

**Comment by ThePix** [comment]
Fixed in next release. Thanks KV.
