### ISSUE TITLE
Desktop GUI horizontal scroll bar missing

### ISSUE THREAD

**Issue by tass23** [textadventures/quest#926]
I created a complex set up of nested IFs recently and noticed that if you IF too far, you cannot edit anything on the right because it is off the screen and there is no scrollbar.

I suppose reducing the amount of nested IFs might be a better alternative, but I thought I would mention it.

**Comment by KVonGit** [comment]
Hello.

I didn't check Quest 5.7.2, but 5.8 (coming soon) has the horizontal scrollbar in the scripts' fields in the GUI.

**Comment by alexwarren** [comment]
Closing out old issues. Please re-open with any additional repro steps if this is still a problem.
