### ISSUE TITLE
FemalePossessive not being updated

### ISSUE THREAD

**Issue by thanosxxx** [textadventures/quest#943]
When the type of an object is changed to **Inanimate Object (feminine)**, (in LanguageSpecificObjectTypes), the FemalePossessive is not being updated - while the same thing *does* work for the male and neutral genders.

**Comment by thanosxxx** [comment]
Masculine and Neutral possessive are defined in lines 80-81. Female possessive is defined in line 82.

Yes, mascuiline and neutral use the same one. I changed the neutral and did some testing. Here's what I found: 

When an inanimate object is introduced, it seems to get its "Possessive" article from NeutralPossesive, line 80. Subsequent updates of the item to Inanimate Object (Male), Inanimate Object (Female) do update its "Gender" and "Article" fields, but not the "Possessive" field.

**Comment by ThePix** [comment]
The female possessive for a person is defined on line 82, and I see "της" for female and "του" for male when changing between male and female people. The LanguageSpecificObjectTypes are defined lines 365 to 378. I tried adding a possessive there and it works.

**Comment by thanosxxx** [comment]
Confirmed, that's it. I'm closing the issue.

(The logic is a bit strange for Greek, though, and I guess for all languages with gendered nouns. The articles depend only on the gender, and not on whether the noun is inanimate or not. I'll study Quest a bit more, and come back with a more concrete proposal later.)

**Comment by ThePix** [comment]
It is trying to do two things at once, which makes sense in English. In Greek (or most other European langages), you would implement it with two drop downs, one for gender, and another for animate/inanimate to determine which display verbs to show, etc.
