### ISSUE TITLE
Quest 5.80beta1: Create an exit shows all objects, not only rooms.

### ISSUE THREAD

**Issue by thanosxxx** [textadventures/quest#956]
As the title says.

**Comment by KVonGit** [comment]
It's done that since 5.6.3, if not earlier versions.  (I found Quest when it was at 5.6.3, so it may have always done this, as far as I know.)

Anyway, the editor just shows a list of objects.  I don't think it can be filtered, but I'm looking into it right now.

**Comment by KVonGit** [comment]
Sorry, but I don't see a way to change that.

Luckily, I'm not in charge around here, though.  Someone else may know a way to pull it off.

**Comment by ThePix** [comment]
It has done that since 5.0.

In Quest, there is no real distinction between rooms and objects in game. The idea is that there might be a box you could go inside, so both an object and a room, so a feature, not a bug.

**Comment by thanosxxx** [comment]
Fair enough, closing issue.
