### ISSUE TITLE
Instructions for Internationalization in Visual Basic

### ISSUE THREAD

**Issue by 8ne** [textadventures/quest#967]
## Hi, I have created a tutorial gif to explain how to use the templates for internationalization:

![instructions_for_internationalization](https://user-images.githubusercontent.com/30032863/39600500-362a1f96-4f1f-11e8-94ca-33a4ac096f92.gif)

**Comment by KVonGit** [comment]
Are you doing that in Visual Studio?

**Comment by SoonGames** [comment]
Yes.

**Comment by SoonGames** [comment]
Since this is not a problem (but rather a solution ^^) I saved the GIF in my account under the following link:

https://github.com/SoonGames/quest_accessories/blob/master/Instructions_for_Internationalization/Instructions_for_Internationalization.gif
