### ISSUE TITLE
Oh jeez. Image problem

### ISSUE THREAD

**Issue by text22** [textadventures/quest#969]
I have been working on a game called (Mario) The Music Box (GameBook Edition) and now it wont let me edit it. When i open it The Screen is grey and it says ,"System.NotSupportedException: No imaging component suitable to complete this operation was found. ---> System.Runtime.InteropServices.COMException: The component cannot be found. (Exception from HRESULT: 0x88982F50)
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at TextAdventures.Quest.EditorControls.FileDropDown.RefreshFileList()
   at TextAdventures.Quest.EditorControls.FileControl.Populate(IEditorData data)
   at TextAdventures.Quest.EditorControls.ElementEditor.Populate(IEditorData data)
   at TextAdventures.Quest.WPFElementEditor.Populate(IEditorData data)
   at TextAdventures.Quest.Editor.ShowEditor(String key)
   at TextAdventures.Quest.Editor.ctlTree_SelectionChanged(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.ChangeSelection(String key)
   at TextAdventures.Quest.EditorControls.WFEditorTree.SelectCurrentTreeViewItem()
   at TextAdventures.Quest.EditorControls.WFEditorTree.ctlTreeView_AfterSelect(Object sender, TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   at System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   at System.Windows.Forms.TreeView.WmNotify(Message& m)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)" I am so confused. Before it all started i was trying to drag a image into my quest. I will send you the quest project and the image so you can fix it. I've been working hard on the project. HELP!!!

**Comment by KVonGit** [comment]
Hello.

Sorry to hear you're having troubles.

If you post a link to the files you have in your game's folder, I will see what I can do.

---
Note that I am just a Quest user.  So I can't make any promises, but I will try my best to help out.  

It actually sounds more like a user settings issue than a problem with the code to me, but I may something.  You never know.

---
I do have one question:

Do other games work?

**Comment by text22** [comment]
YES, All of my other games work. here is the file:
[Problem.zip](https://github.com/textadventures/quest/files/1978108/Problem.zip)

**Comment by KVonGit** [comment]
I'm investigating this right now.

Which Windows are you running, and which version of Quest?

**Comment by KVonGit** [comment]
It's something with Quest's latest beta.

It opens and runs for me with quest580beta1, but that is no longer listed, so I advise dropping back to 5.7.2 for now.  The added features shouldn't allow you to do anything extra in a gamebook, anyway.

Sorry about that.  I'm trying to find what change causes this.  If I can't, Pixie probably can.

Here's a link to Quest 5.7.2:


https://github.com/textadventures/quest/releases/tag/5.7.2

**Comment by KVonGit** [comment]
Found a link to 5.8.0beta1, which loads your game for me:

https://github.com/textadventures/quest/releases/download/5.8.0-beta.1/quest580beta1.exe

Let me know if this works (or doesn't work), please.

**Comment by KVonGit** [comment]
In Quest 5\Core\Languages\EditorEnglish.aslx

These lines of code (at the beginning) are preventing the editor from opening a gamebook (but not a text adventure):

```xml
  <template name="DevModeCommandPut">put</template>
  <template name="DevModeCommandDrop">drop</template>
  <template name="DevModeCommandTake">take</template>
  <template name="DevModeCommandTo">to</template>
  <template name="DevModeCommandGo">go</template>
  <template name="DevModeCommandOpen">open</template>
  <template name="DevModeCommandClose">close</template>
  <template name="DevModeCommandOn">on</template>
  <template name="DevModeCommandOff">off</template>
  <template name="DevModeCommandClr">clr</template>
  <template name="DevModeCommandHelp">?</template>
  <template name="DevModeCommandsInVerbs">#drop;#take;#to;#open;#close;#on;#off</template>
  <template name="DevModePattern"><![CDATA[^(?<command2>put) (?<object1>.+) (in|on) (?<object2>.+)$|^(?<command1>drop|take|to|go|open|close|on|off) (?<object>.+)$|^(?<command0>clr|\?)$]]></template>
  <template name="DevModeErrorWrongFormat">Unfortunately, this is the wrong format.</template>
  <template name="DevModeErrorObjectNotRecognised">The object was not detected.</template>
  <template name="DevModeErrorWrongTyp">That´s the wrong typ.</template>
  <template name="DevModeErrorWrongKey">The key was not found.</template>
  <dynamictemplate name="DevModeErrorCantFindObject">"The object with the name '" + text + "' cannot be found."</dynamictemplate>
  <dynamictemplate name="DevModeErrorCantFindAttribute">"The attribute with the name '" + text + "' cannot be found."</dynamictemplate>
  <template name="DevModeExecuteCommand">The command was executed.</template>
  <template name="DevModeNotActive">The DevMode is not active!</template>
  <template name="DevModeDescriptionCommands"><![CDATA[<b>Commands</b><br/>#take object<br/>#drop object<br/>#put object1 in object2<br/>#open object<br/>#close object<br/>#on objekt<br/>#off objekt<br/>#to player<br/>#go raum<br/><br/><i>Unlike the commands in the game, they are executed directly and without detours via intercept scripts.</i><br/><br/><b>Expressions</b><br/>#object1.attribut=object2.attribut (attribute assignment of another object)<br/>#object.attribut=true/false (boolean)<br/>#?object.attribut (set true)<br/>#!object.attribut (set false)<br/>#object.attribut="value" (string)<br/>#object.attribut=15 (integer)<br/>#object.attribut=25.55 (double)<br/>#object.attribut=[item1;item2;item3] (list)<br/>#object.attribut[]=element (add element to list)<br/>#object.attribut=[] (create new list)<br/>#object.attribut={key1:item1;key2:item2;key3:item3} (dictionary)<br/>#object.attribut{key}=element (add or overwrite element to dictionary)<br/>#object.attribut={} (create new dictionary)<br/>#object.attribut (read attribute)<br/><br/><b>Extras</b><br/>#clr (clear screen)<br/>#? (help)<br/># (close game)]]></template>
  <template name="DevModeDescriptionAttribute"><![CDATA[Enter the object with the corresponding attribute in "Key" (e. g. game.showtitle or player.look). The assignment is entered in "Value". It is possible to create Strings ("Hello World!"), Boolean (true or false), Integer (15), Double (25.55), Listen (["Hello";"World";"!"]) and Dictionarys ({H:"Hello";W:"World"}.)]]></template>
  <template name="EditorGameDevMode">Developer-Mode</template>
  <template name="EditorGameDevModeInfoRelease">Important: Before releasing the game the developer mode must be deactivated!</template>
  <template name="EditorGameDevModeInfoCommands">Enhanced commands are available in the current game. Enter '#?' to get more information.</template>
  <template name="EditorGameDevModeOptions">Options</template>
  <template name="EditorGameDevModeChangePov">Select another player</template>
  <template name="EditorGameDevModeChangePovPos">Select another position of the player</template>
  <template name="EditorGameDevModePov">Player</template>
  <template name="EditorGameDevModePlace">Place</template>
  <template name="EditorGameDevModeSetInitScript">Use an initialization script for the developer mode</template>
  <template name="EditorGameDevModeInitScript">Initialization script for the developer mode</template>
  <template name="EditorGameDevModeSetVerbs">Adding verbs of development mode to the verb list of objects</template>
  <template name="EditorGameDevModeShowInfos">Display development mode output</template>
  <template name="EditorGameDevModeOwnFontColour">Use your own font color for the developer mode output</template>
  <template name="EditorGameDevModeFontColour">Font color for developer mode output</template>
  <template name="EditorGameDevModeOn">Activ</template>
  <template name="EditorGameDevModeOff">Inactiv</template>
  <template name="EditorGameDevModeAttributes">Attributes</template>
  <template name="EditorGameDevModeActive"><![CDATA[<b>DevMode: Activ</b>]]></template>
  <template name="EditorGameDevModeChangedPov">DevMode: Change player object.</template>
  <template name="EditorGameDevModeChangedPovPos">DevMode: Change player position.</template>
  <template name="EditorGameDevModeChangedAttributes">DevMode: Set attributes.</template>
  <template name="EditorGameDevModeStartScript">DevMode: Start initialization script.</template>
```

**Comment by KVonGit** [comment]
@ThePix 

I copied the old EditorEnglish.aslx and renamed it GamebookEditorEnglish.aslx.  Then, I dropped that into Core\Languages and changed the line in GamebookCore.aslx to include GamebookEditorEnglish.aslx instead of EditorEnglish.aslx.  Everything worked fine this way.

(Nothing being added is effecting gamebook functionality anyway; right?)

---
PS

If you like the idea of this change, I propose that we add ShowMenu to GamebookCore.aslx while we're editing.  I've added the functions into quite a few gamebooks, and it doesn't hurt anything as far as I can discern.

http://textadventures.co.uk/forum/quest/topic/phlhxhlrak_j3qns2icxbg/can-gamebooks-use-showmenu#3d7982e9-e206-4ac4-af3d-a83cf24d50cd

**Comment by KVonGit** [comment]
UPDATE

I uninstalled 580beta2.  I downloaded it again.  I installed that, and gamebooks work.

---
So, I decided to delete quest\ from my hard drive and clone it again as if it were new, to see if that solved the same issue with the current build.  

When I build what's currently in the repo, the gamebooks will not open in the editor.  So, just because I don't trust myself, I removed all of the code from my recent commits, but that didn't fix it.  

---
Next, I deleted the DevMode templates from English.aslx (again; this is a newly cloned repo), and the gamebook opened in the editor again, just like before

...but there is another problem.  This is what a new gamebook with nothing added prints when I press 'Play':

```
This is page 1. Type a description here, and then create links to other pages below.


Error running script: Cannot foreach over '' as it is not a list
Error running script: Error compiling expression 'Instr(text, "{")': FunctionCallElement: Could find not function 'Instr(Object, String)'


Error running script: Cannot foreach over '' as it is not a list
Error running script: Error compiling expression 'Instr(text, "{")': FunctionCallElement: Could find not function 'Instr(Object, String)'
```

**Comment by KVonGit** [comment]
# UPDATE (found the fix)

The file GamebookCore.aslx has its own ```defaultgame``` object.

I added the new text processor game attributes to it, and the gamebook is functional.

<details>

```xml
<!-- Scripts used by the text processor -->
    <textprocessorcommands type="scriptdictionary">
      <item key="if ">
        game.textprocessorcommandresult = ProcessTextCommand_If (section, data)
      </item>
      <item key="either ">
        game.textprocessorcommandresult = ProcessTextCommand_Either (section, data)
      </item>
      <item key="here ">
        game.textprocessorcommandresult = ProcessTextCommand_Here (section, data)
      </item>
      <item key="nothere ">
        game.textprocessorcommandresult = ProcessTextCommand_Here (section, data)
      </item>
      <item key="popup:">
        game.textprocessorcommandresult = ProcessTextCommand_Popup (section, data)
      </item>
      <item key="i:">
        game.textprocessorcommandresult = ProcessTextCommand_Format (section, data)
      </item>
      <item key="b:">
        game.textprocessorcommandresult = ProcessTextCommand_Format (section, data)
      </item>
      <item key="s:">
        game.textprocessorcommandresult = ProcessTextCommand_Format (section, data)
      </item>
      <item key="u:">
        game.textprocessorcommandresult = ProcessTextCommand_Format (section, data)
      </item>
      <item key="colour:">
        game.textprocessorcommandresult = ProcessTextCommand_Colour (section, data)
      </item>
      <item key="color:">
        game.textprocessorcommandresult = ProcessTextCommand_Colour (section, data)
      </item>
      <item key="back:">
        game.textprocessorcommandresult = ProcessTextCommand_Colour (section, data)
      </item>
      <item key="object:">
        game.textprocessorcommandresult = ProcessTextCommand_Object (section, data)
      </item>
      <item key="command:">
        game.textprocessorcommandresult = ProcessTextCommand_Command (section, data)
      </item>
      <item key="page:">
        game.textprocessorcommandresult = ProcessTextCommand_Command (section, data)
      </item>
      <item key="exit:">
        game.textprocessorcommandresult = ProcessTextCommand_Exit (section, data)
      </item>
      <item key="once:">
        game.textprocessorcommandresult = ProcessTextCommand_Once (section, data)
      </item>
      <item key="notfirst:">
        game.textprocessorcommandresult = ProcessTextCommand_NotFirst (section, data)
      </item>
      <item key="random:">
        game.textprocessorcommandresult = ProcessTextCommand_Random (section, data)
      </item>
      <item key="rndalt:">
        game.textprocessorcommandresult = ProcessTextCommand_RandomAlias (section, data)
      </item>
      <item key="img:">
        game.textprocessorcommandresult = ProcessTextCommand_Img (section, data)
      </item>
      <item key="counter:">
        game.textprocessorcommandresult = ProcessTextCommand_Counter (section, data)
      </item>
      <item key="select:">
        game.textprocessorcommandresult = ProcessTextCommand_Select (section, data)
      </item>
      <item key="eval:">
        game.textprocessorcommandresult = ProcessTextCommand_Eval (section, data)
      </item>
      <item key="=">
        game.textprocessorcommandresult = ProcessTextCommand_Eval (section, data)
      </item>
    </textprocessorcommands>
```
</details>

---
# I had to...

1\. Remove the DevMode templates from EditorEnglish.aslx  (I also removed DevMode.aslx from the includes in Core.aslx, but I don't know if this step is necessary.)

2\. Add the text processor attribute to ```defaultgame``` in GamebookCore.aslx.

**Comment by KVonGit** [comment]
These two dynamic templates are the problem.

```xml
  <dynamictemplate name="DevModeErrorCantFindObject">"The object with the name '" + text + "' cannot be found."</dynamictemplate>
  <dynamictemplate name="DevModeErrorCantFindAttribute">"The attribute with the name '" + text + "' cannot be found."</dynamictemplate>
```

**Comment by SoonGames** [comment]
I could also make normal templates out of it. This is not so important if you are dynamic. Wouldn't that be a better solution? Or isn't it the only problem?

P.S.: I think discussing it here is more appropriate. I've been looking in here more often now. Promised. ^^

**Comment by KVonGit** [comment]
I moved the DevMode command templates to English.aslx.  (I guess the editor can't handle dynamic templates in gamebook mode?)

Anyway, everything runs smoothly this way, and the two pull requests have been submitted.

---
The first thing I did was change them to normal templates, but once I found I could simply move the command stuff to English.aslx (which is where I think it belongs anyway), everything worked out perfectly.

**Comment by KVonGit** [comment]
>I've been looking in here more often now.

I am "Watching" this repository, so I get an email each time something happens (including Issues, Pull Requests, and commits).  It seems easier than remembering to check in.

**Comment by KVonGit** [comment]
@SoonGames 

It's your code, so don't let me do something you don't like with it.  I was just finding a good, clean, quick fix.

If you'd like to handle it differently, I can delete my pull requests and defer to you.

**Comment by SoonGames** [comment]
> It's your code, so don't let me do something you don't like with it. I was just finding a good, clean, quick fix. If you'd like to handle it differently, I can delete my pull requests and defer to you.

No. That's all right. As long as it works. ;-)
I was just desperately looking for a way to quote. ^^

**Comment by SoonGames** [comment]
That's right. You could move all commands to be executed in the command field (i.e. all templates from DevMode without "Editor" in front of it) to English.aslx or Deutsch.aslx.

**Comment by SoonGames** [comment]
Oh, yeah. You did. Perfect.

**Comment by SoonGames** [comment]
The German.aslx or EditorGerman.aslx would have to be changed accordingly. Are you gonna do this or can I do it fast?

**Comment by KVonGit** [comment]
> The German.aslx or EditorGerman.aslx would have to be changed accordingly. Are you gonna do this or can I do it fast?

You better do it.  (I wish I could sprechen sie Deutcsh!)

---
PS

I also added a template called ```EditorGameEnableDevMode``` to EditorEnglish for a checkbox in the game's features which enables DevMode.

If this is not checked, the DevMode tab will be hidden.

See pull requests:

https://github.com/textadventures/quest/pull/975

https://github.com/textadventures/quest/pull/976

https://github.com/textadventures/quest/pull/977

**Comment by SoonGames** [comment]
> I also added a template called EditorGameEnableDevMode to EditorEnglish for a checkbox in the game's features which enables DevMode.

Yeah, that's all right.

**Comment by text22** [comment]
Can you send me the file you fixed?

**Comment by KVonGit** [comment]
I changed a few different files, and they are all sort of in GitHub limbo at the moment.

ThePix will either merge them or apply his own (better and more efficient) fix soon.  


---
I uninstalled Quest, downloaded the quest580beta2 installer again, installed that, and everything worked fine.

If that doesn't work for you, and you want to run the beta version, I'd try to download and install quest580beta1:

https://github.com/textadventures/quest/releases/download/5.8.0-beta.1/quest580beta1.exe

...or, to be safe, you could just run the current release:

https://github.com/textadventures/quest/releases/download/5.7.2/quest572.exe

---
You are running Quest 580beta2, correct?

That was the only version of Quest I had problems opening your game with at first, but I did not have the image files, so Quest ignored them once I got Quest running.  So, there still *could* be an issue with an image you're using, and I just happened to find a different bug while investigating your problem.

**Comment by ThePix** [comment]
I have merged the push requests, and it works for me now. I will put up a new beta in a couple of days.

**Comment by text22** [comment]
THANKS!!!
