### ISSUE TITLE
Changing ASL version 550 to 580 will cause errors in existing games

### ISSUE THREAD

**Issue by ThePix** [textadventures/quest#984]
I plan to change the ASL version to 580 in Quest 5.8, so your game will, on the second line, say 
```
<asl version="580">
```
This is because there are some changes to the underlying C# code, and it tells Quest the player (and editor) must be version 5.8 to run properly. The last time this changed was for Quest 5.5, and in hindsight that may not have been a good thing (note that 5.6 was released by Alex, and I was following his lead in Quest 5.7).

If you upgrade to Quest 5.8, you will be able to open any game to edit it. When you save (but not autosave, strangely), the game will automatically become a 5.8 game.

However, there may be a problem with playing games from Quest 5.6 and Quest 5.7. Because they will say 550 at the top, it looks like Quest will try to play them with Quest 5.5, and if there are any new features since then, it will generate errors.

How does it do that? There must be something in the player that checks what the game version is, and then selects the latest Quest version, getting the core library from where?

As far as I can tell, published games are okay, as they include all the core libraries anyway.

Do we have a big problem? Or does it not actually matter?

**Comment by KVonGit** [comment]
> How does it do that? There must be something in the player that checks what the game version is, and then selects the latest Quest version, getting the core library from where?

I'm looking around in WorldModel\GameLoader\.  I think that's where the magic happens, but this C# is hard to read sometimes...

**Comment by KVonGit** [comment]
Wow!

Okay, I'm loading my game made in 5.7.2:  Survival Quest.

It is ASL version 550.

![image](https://user-images.githubusercontent.com/30656341/39924470-818457f8-54ed-11e8-84ea-d4ef17ec5d59.png)

---
Note the object links:

![image](https://user-images.githubusercontent.com/30656341/39924496-a0935f5e-54ed-11e8-8023-c2c59a2c71a9.png)


---
A simple change from 550 to 580 in full code view:

![image](https://user-images.githubusercontent.com/30656341/39924505-b27f608c-54ed-11e8-8643-0817fcd5a3f8.png)


---
...and the text processor stuff now works:

![image](https://user-images.githubusercontent.com/30656341/39924512-bf30f070-54ed-11e8-9455-7026130f4a1e.png)


---
In WorldModel\WorldModel\GameLoader\GameLoader.cs:

It *looks like* lines 125 and 126 tell Quest which core stuff to load, depending on the ASL version.

**Comment by ThePix** [comment]
Okay... But that means the desktop version has a copy somewhere of the core libraries of every version of Quest 5. I have searched Visual Studio for things in the core libraries numerous times, and not stumbled across earlier versions. I guess we have both searched for "550" and not found anything that says load these alternative core libraries.

**Comment by KVonGit** [comment]
Autosave just changed my game to 580.

First, I loaded the game, pressed play, pressed stop, flipped to code view, and it was still 550.

Then, I changed the game version in the GUI,  pressed play, pressed stop, flipped to code view, and it was 580.

**Comment by KVonGit** [comment]
> that means the desktop version has a copy somewhere of the core libraries of every version of Quest 5.

It can't be doing that (I don't think).  Because **I have searched Visual Studio for things in the core libraries numerous times, and not stumbled across earlier versions**, too.

I theorize it is ignoring Core libraries when it finds a lower ASL version.

There has to be something else like this somewhere:

```C#
               case Request.Pause:
                    if (m_worldModel.Version >= WorldModelVersion.v550)
                    {
                        throw new Exception("The 'Pause' request is not supported for games written for Quest 5.5 or later. Use the 'SetTimeout' function instead.");
                    }
```

**Comment by ThePix** [comment]
Hmm, maybe I had not changed anything, so it did not autosave before I did play.

**Comment by ThePix** [comment]
I had a game with `DiceRoll(4)` in it. Worked fine in 5.7, because 5.7 changed `DiceRoll` to take ints as well as strings. When I went to 5.8 in the editor, it failed, because it was expecting a string.

Quest 5.5, ASL 550: Would have failed
Quest 5.7, ASL 550: Works fine
Quest 5.8, ASL 550: Fails, as though it was Quest 5.5
Quest 5.8, ASL 580: Works fine

**Comment by KVonGit** [comment]
Okay...

When I leave it "550", I open the debugger, and the game object has the text processor attribute setup.  So, CoreTypes is definitely being loaded.  (I've decided a process of elimination may be the best route to take.)

---
I may be able to make a popup when loading an aslx file in the editor which has an ASL version lower than 580.

"The file you have loaded has a lower version number than the current build.  Your game will probably not work unless you change the asl version to 580 (and possibly edit some of your code)."

Something to that effect, anyway.

---
All in all, though, I still think changing the ASL version seems like a good thing.

It seems to be more for the player than for the author.  If a player tries to play a new game on an old version of Quest, it will not load.  They won't waste time playing a game which will eventually mess up in one way or the other, and they won't run into mysterious errors during play, therefore they won't contact the author about said errors.  (I don't think most authors would even think to connect ASL version dots, but I may be mistaken.)

Anyway, it looks like the only issues are related to editing an existing .aslx file.  If you load one in the editor and don't change the ASL version (and don't change anything else, which would automatically change the ASL version), your game will not work correctly.  Now, who would do this without testing their game out?  I probably would, but I would deserve the repercussions. Would I not?

---
Now, this is just confusing:  I just loaded an .aslx file with version 550.  I immediately pushed 'Publish'.  

The created game file says version 550, but THE THINGS THAT DID NOT WORK WHILE PLAYING THIS GAME IN THE EDITOR DO WORK IN THE .QUEST FILE.  (For instance, the text processor does not work while playing a 550 game from the editor, but it does work in a published file with version 550.

???

I mean, this is a good thing...  I guess...  but I am now thoroughly confused.

---
I still say the new version number is good for the player.  The player is innocent, only wanting to play a game.

An author, on the other hand, asked for trouble as soon as he or she decided to create and publish a computer game.  If the author has problems during an update, he or she can get help on the forum or create an issue on GitHub.

**Comment by KVonGit** [comment]
Aha!   I think I found the problem.

In WorldModel\WorldModel\Scripts\ReturnScript.cs, on line 48, change v580 to v550, then try out a game with version 550 in the editor.

```C#
            if (m_worldModel.Version >= WorldModelVersion.v550) c.IsReturned = true;

```

**Comment by ThePix** [comment]
> In WorldModel\WorldModel\Scripts\ReturnScript.cs, on line 48, change v580 to v550, then try out a game with version 550 in the editor.

What is that line doing? I cannot look right now, but I feel it should be 580.

**Comment by KVonGit** [comment]
Oh, sorry.  Here's the entire block:

```C#
        public override void Execute(Context c)
        {
            c.ReturnValue = m_returnValue.Execute(c);
            if (m_worldModel.Version >= WorldModelVersion.v550) c.IsReturned = true;
        }
```

---
I *think* it's preventing preventing C# code from being executed when the ASL version of the loaded game is less than v580.  

If this is true, I shouldn't be able to save a game I published with 5.7.2, correct?

**Comment by KVonGit** [comment]
>If this is true, I shouldn't be able to save a game I published with 5.7.2, correct?

I don't know what made me think saving wouldn't work, but it is not the case.

I guess I need to quickly learn what exactly Execute is doing, because it definitely makes 550 games work when played from the editor.  I can't find anything else that's effected.

**Comment by KVonGit** [comment]
Ah...  THIS is the *entire* block of code (which explains why saving a game still worked either way):

```C#
public class ReturnScript : ScriptBase
    {
        private ScriptContext m_scriptContext;
        private WorldModel m_worldModel;
        private IFunctionGeneric m_returnValue;

        public ReturnScript(ScriptContext scriptContext, IFunctionGeneric returnValue)
        {
            m_scriptContext = scriptContext;
            m_worldModel = scriptContext.WorldModel;
            m_returnValue = returnValue;
        }

        protected override ScriptBase CloneScript()
        {
            return new ReturnScript(m_scriptContext, m_returnValue.Clone());
        }

        public override void Execute(Context c)
        {
            c.ReturnValue = m_returnValue.Execute(c);
            ' I have changed this back to v550. Now everything appears to work correctly. - KV
            if (m_worldModel.Version >= WorldModelVersion.v550) c.IsReturned = true;
        }

        public override string Save()
        {
            return SaveScript("return", m_returnValue.Save());
        }

        public override string Keyword
        {
            get
            {
                return "return";
            }
        }

        public override object GetParameter(int index)
        {
            return m_returnValue.Save();
        }

        public override void SetParameterInternal(int index, object value)
        {
            m_returnValue = new ExpressionGeneric((string)value, m_scriptContext);
        }
    }
```

**Comment by KVonGit** [comment]
Yes.

For backwards compatibility, this line needs to be v550.

I load a game published with 5.7.2 in 58beta3, and I have problems:

![image](https://user-images.githubusercontent.com/30656341/39935285-1f20fdc0-550e-11e8-9711-a6f3ba55522b.png)


---
...but the same game loaded in my build (which is identical to 58beta3, except I changed this one line of code) works:

![image](https://user-images.githubusercontent.com/30656341/39935317-3e507400-550e-11e8-96f9-32c06f719a81.png)


---
I found that Execute is handling pretty much everything.

**Comment by KVonGit** [comment]
Are you reading this thread, @Pertex ?

(Your input is highly valued, good sir.)

**Comment by ThePix** [comment]
The files in WorldModel\WorldModel\Scripts handle the script command, with one file per command, so the ReturnScript.cs file is just for `return`. The `execute` method is what actually does the work. All the rest is  creating and saving the command, and handling parameters.

At one time `return` behaved a bit oddly. It just set the value the function would return, but did not stop the function; if there was more code in the function, that would still run. It may be that the `execute` checks which version to see whether it should do it the old way or the new way.

 I have not had a chance to test your fix yet, but I think we need to move to 580 one way or another.

**Comment by KVonGit** [comment]
> It may be that the execute checks which version to see whether it should do it the old way or the new way.

Yeah, it looks like it checks which version to see whether it does certain things at all (and how it handles a handful of specific things).  

For instance, it will save the game, but it won't perform text-processor stuff.  The text-processor stuff not working baffles me.  When I check the debugger, the text processor attribute is definitely set on the game, but nothing works when it's set to 550.  I just created a new game in 580beta3.  I only added a stick with a description.  I flipped to code view, changed the version to 580, and pressed play:


---
Transcript enabled for:

TITLE: | Whiskey Tango Foxtrot?!?!
-- | --
VERSION: | 1.0
IFID: | cc5b61cf-330e-4ec3-b81d-051576011396



[ Enter SCRIPT OFF to disable the transcript. ]

\> look
You are in a room.
You can see a {object:stick}.

\> x stick
I can't see that.

\> examine stick
I can't see that.

\> look at stick
I can't see that.

\> take stick
You can't take it.

\* Now, I shall click on 'Look at' stick from the Places and Objects pane...
Noted.

\> look at {object:stick}
It's just a stick.

\* Odd.
Noted.

\> view script

---
NOTE:  I need to remove that table when printing the game info upon enabling the transcript.  It messes up copying and pasting.

**Comment by ThePix** [comment]
This seems to have been resolved.
