### ISSUE TITLE
The DevMode does not work properly anymore

### ISSUE THREAD

**Issue by SoonGames** [textadventures/quest#986]
The DevMode does not work properly anymore.

He no longer finds the templates that are addressed by function (Template("DevMode...")): Error running script: Error evaluating expression 'Template("DevModePattern")': No template named 'DevModePattern'

You know what could be the reason?

Furthermore I have the suggestion to insert the DevMode call in the Core.aslx before the user interface:

    if (game.feature_devmode) {
      setDevMode
    }
    InitUserInterface
    if (HasScript(game, "inituserinterface")) {
      do (game, "inituserinterface")
    }

What do you think of that?

**Comment by KVonGit** [comment]
I haven't seen that error.  I'll see what I can dig up.  

I see this error when I start a game with DevMode enabled, though:

```
DevMode: Activ
Error running script: Error compiling expression 'game.devmode_setinitscript and HasScript(game, "devmode_initscript")': AndOrElement: Operation 'And' is not defined for types 'Object' and 'Boolean'
```

---
> Furthermore I have the suggestion to insert the DevMode call in the Core.aslx before the user interface:

I'm not in charge, but that is already automatically added to Init User Interface when I enable DevMode.

**Comment by KVonGit** [comment]
> that is already automatically added to Init User Interface when I enable DevMode.

...but I don't see how it could hurt if you moved it to ```InitInterface``` in Core.aslx, either.  Unless Pixie is leery of changing anything that currently works.  (We've added a LOT of stuff to this version of Quest.)

**Comment by KVonGit** [comment]
Changing this line in ```setDevMode``` resolve the issue I was having:

OLD
```c
if (game.devmode_setinitscript and HasScript(game, "devmode_initscript")) {
```

NEW
```c
if (not game.devmode_setinitscript = null and HasScript(game, "devmode_initscript")) {
```

**Comment by SoonGames** [comment]
Thank you. Fixed the error by adding devmode_settinitscript to the types. It's actually working now. Only with my already created game the error with the templates still comes. Let's see what's causing this.

**Comment by KVonGit** [comment]
Is your library still added to the game?  If so, the old library is probably overriding the new built-in DevMode functions, and we added those templates recently (I think).

**Comment by KVonGit** [comment]
I already had the file open in a branch, so I went ahead and submitted a pull request: #987

**Comment by SoonGames** [comment]
No. Stop. I'll change more anyway. This is also about a boolean type that queries whether a DevMode script is used or not. So it would only test if the variable exists.

**Comment by SoonGames** [comment]
No problem. I can also run ahead sometimes. ;-)

**Comment by SoonGames** [comment]
Okay. Done.
